Substra/substra-backend

backend/substrapp/serializers/ledger/traintuple/serializer.py

The `rank` property was declared twice in the traintuple serializer, this PR removes the first declaration that was overwritten by the second.

Remove duplicate declaration of property

---

charts/substra-backend/Chart.yaml

During the "users" mission the chart got modified but the version of the chart was not bumped resulting in the version not being usable from the public registry.

Bump chart version

---

.travis.yml

The deployment was failing due to the step `cd backend` resulting in the following error in travis:
```
Error: could not find /home/travis/build/SubstraFoundation/substra-backend/backend/charts/substra-backend: stat /home/travis/build/SubstraFoundation/substra-backend/backend/charts/substra-backend: no such file or directory
```
I initially thought that the context, aka the current directory was reset from a stage to another but I was wrong obviously :P As this doesn't trigger a build failure as it's an `after` step it was hard to spot. Sorry about that

Fix deployment through travis

---

.gitignore

In Skaffold watch mode, each time you change a file, Skaffold generate some temporary files in the current workspace. Those files could be added mistakenly to the git stage.

update gitignore file to ignore tmp charts files

---

backend/substrapp/tasks/tasks.py
backend/substrapp/tests/assets.py
backend/substrapp/tests/tests_tasks.py
backend/substrapp/tests/views/tests_views_tuples.py

See also: https://github.com/SubstraFoundation/substra-chaincode/pull/21
--- 
Instead of accessing `model.hash` and `model.storageAddress` directly, use the new `testtuple.traintupleKey` field. Use that traintuple key to obtain the model hash and storage address by requesting the traintuple metadata. 
Since traintuples and testtuples now have a different structure, update the name of function parameters to make it clear which functions take a `traintuple` or a `testtuple` as an argument.

Testtuples: Use reference to traintuple instead of using direct reference to model

---

backend/substrapp/tests/views/tests_views_compositealgo.py
backend/substrapp/tests/views/tests_views_compositetraintuples.py
backend/substrapp/views/compositealgo.py
backend/substrapp/views/compositetraintuple.py
backend/substrapp/views/filters_utils.py

In this PR:
Use `composite_algo` and `composite_traintuple` as asset keywords in filters instead of `compositealgo` and `compositetraintuple` to harmonize with the URLs and the denominations of assets in the cli / frontend.
Apply `composite_algo` filters on `algo` assets and vice versa. This means that requesting `/compositealgo?search=algo:key:foo` will return no results instead of previously returning all results.
This last change allows to query both `/algo` and `/compositealgo` with the same search string and be able to treat the responses as part of a larger query on all types of algos.

Handle algo and composite algo as similar in filters

---

.dockerignore

The .dockerignore will prevent tests from being included in containers. Which also means that while running `skaffold dev`, we'll be able to edit tests without seeing the images being rebuilt continuously.

Do not include tests in containers

---

.dockerignore
backend/substrapp/tests/assets.py
backend/substrapp/tests/generate_assets.py
backend/substrapp/tests/views/tests_views_computeplan.py
backend/substrapp/views/computeplan.py
backend/substrapp/views/filters_utils.py

Add routes to list and retrieve compute plans.
~~This PR depends on a chaincode update: https://github.com/SubstraFoundation/substra-chaincode/pull/22~~ Merged!
In order to add compute plans to the tests assets fixtures, I wanted to run generate_assets.py against  skaffold instead of docker-compose. I updated the script with a `-s` option that will use our standard skafold dev env.
In order to fully test this PR, you'll need the companion PR in the cli/SDK: https://github.com/SubstraFoundation/substra/pull/24
Then:
1. Run the populate.py
2. Try `substra list compute_plan` and `substra get compute_plan <key>`
3. Use DRF's browsable API and navigate to `/compute_plan/`
NB: the assets.py fixtures will have to be re-generated once the related chaincode PR is finalized.

List and retrieve compute_plans

---

.travis.yml

Since TravisCI is executing helm 3.0, and according to the migrate document, https://helm.sh/docs/topics/v2_v3_migration/ the `--client-only` is not supported anymore as it is the default behavior.
Let's make our CI great again ✌️

fix helm init command since helm upgrade to 3.0 

---

backend/substrapp/serializers/ledger/aggregatealgo/serializer.py
backend/substrapp/serializers/ledger/algo/serializer.py
backend/substrapp/serializers/ledger/compositealgo/serializer.py
backend/substrapp/serializers/ledger/datamanager/serializer.py
backend/substrapp/serializers/ledger/objective/serializer.py
backend/substrapp/tests/query/tests_query_algo.py
backend/substrapp/tests/query/tests_query_datamanager.py
backend/substrapp/tests/query/tests_query_datasample.py
backend/substrapp/tests/query/tests_query_objective.py

Using a dynamic domain name infered from the request can be problematic.
For instance if a request is in https until a firewall/reverse proxy and went to be http inside the infrastructure it can generate conflict.

Fix backend domain name from dynamic to static

---

backend/substrapp/tasks/tasks.py

Local folder is defined for:
- aggregatetuple
- traintuple
- composite_traintuple
All these tuples will share the same local folder (inside a compute plan).

set local folders for all train like tuples

---

backend/backend/settings/dev.py
backend/backend/settings/test.py
backend/substrapp/ledger_utils.py

Fix #67
- fix parsing of fabric-sdk-py exceptions to raise internal MVCC Read Conflict errors
- enable retry for `log_*` in case of Ledger errors by default (was disabled in dev)

Fix MVCC Read Conflict retry

---

backend/substrapp/ledger_utils.py
backend/substrapp/serializers/ledger/aggregatetuple/serializer.py
backend/substrapp/serializers/ledger/compositetraintuple/serializer.py
backend/substrapp/serializers/ledger/computeplan/serializer.py
backend/substrapp/serializers/ledger/testtuple/serializer.py
backend/substrapp/serializers/ledger/traintuple/serializer.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tests/query/tests_query_tuples.py
backend/substrapp/tests/tests_misc.py
backend/substrapp/tests/views/tests_views_computeplan.py
backend/substrapp/views/aggregatetuple.py
backend/substrapp/views/compositetraintuple.py
backend/substrapp/views/testtuple.py
backend/substrapp/views/traintuple.py
populate.py

Tasks:
Companion PRs:
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/50)
- [substra](https://github.com/SubstraFoundation/substra/pull/52)
- [tests](https://github.com/SubstraFoundation/substra-tests/pull/25)

Fail fast: remove evaluation for train like tuples

---

backend/backend/settings/deps/ledger.py
backend/substrapp/ledger_utils.py
backend/substrapp/serializers/ledger/aggregatetuple/util.py
backend/substrapp/serializers/ledger/compositetraintuple/util.py
backend/substrapp/serializers/ledger/testtuple/util.py
backend/substrapp/serializers/ledger/traintuple/util.py
backend/substrapp/tests/tests_misc.py

Fix #72 
- fix bug: retry was called several times for a unique call to the ledger
- when doing an invoke to update a tuple status, don't retry on timeout errors
- when updating a status, in case of timeout wait for status to be as expected
- reordering of methods in ledger_utils: group low level functions requesting the ledger at the top
⚠️  It won't fix #10 and #77: as the fix will work only for the log methods (worker side)

worker: review retry when communicating with ledger in case of timeout

---

backend/backend/settings/common.py
backend/backend/settings/dev.py
backend/backend/settings/prod.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tests/tests_tasks.py

This PR introduces an auto-retry mechanism for compute tasks: up to 5 retries (i.e. 6 attempts in total), with 2 secs between each attempt.
The retry logic is handled by Celery. Most of the changes in this PR are just moving things around. The actual retry logic is only the `raise self.retry(...)` line (!)
:warning: **Following this PR, compute task results and exceptions are now passed back to Celery**. Prior to this PR, the result (or exception) from `do_task` was passed to `log_success_tuple` (or `log_fail_tuple`) and didn't leave the `compute_task` function. That's not the case anymore. Now the result/exception is returned to Celery (via `return` or `raise`). Celery, in turn, either retries, calls `on_succeed` or calls `on_failure`. I don't think that's a problem because 1. I'm not …

Retry a failed task up to 5 times

---

backend/substrapp/tests/views/tests_views_computeplan.py
backend/substrapp/views/computeplan.py

Tasks:
Companion PR:
- [substra](https://github.com/SubstraFoundation/substra/pull/56)
- [chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/53)
- [tests](https://github.com/SubstraFoundation/substra-tests/pull/26)
- [frontend](https://github.com/SubstraFoundation/substra-frontend/pull/33)

Implement cancel compute plan view

---

backend/substrapp/tasks/utils.py
backend/substrapp/tests/tests_misc.py

For Production, we need to get cpu and gpu sets from the docker api and not from the container directly

Update gpu and cpu set function.

---

backend/substrapp/ledger_utils.py

LedgerTimeout errors raised by invoke query on asset creation should be propagated from the chaincode to the substra client.
Actually, the substra sdk has a retry mechanism in case of LedgerTimeout on asset creation (retry till the asset exists).
Issue has been introduced by: https://github.com/SubstraFoundation/substra-backend/commit/da66d0e5f5a9b69f968ac0aa435cabbb185a8b42.

fix: don't retry on LedgerTimeout when doing an invoke

---

backend/substrapp/ledger_utils.py
backend/substrapp/tests/tests_misc.py

- status code was incorrect due the from_response class method returning the base class
- can be tested with: https://github.com/SubstraFoundation/substra-tests/pull/58 (end to end test is not working without this fix)
EDIT:
This fix enables us to discover a new bug: we should not retry ledger request on BadResponseError. We could not see this bug before as the LedgerError was not properly created.

fix ledger error inheritance

---

backend/substrapp/tasks/tasks.py

Task worker is leaking database connections, which leads to too many client pg errors.
This PR force closing old connections in both cases failure or success.
Seems to be related to this issue => https://github.com/celery/celery/issues/5483

force closing old connection on success or failure of tasks

---

backend/substrapp/tasks/tasks.py
backend/substrapp/tests/tests_tasks.py

This aims to fix a bug while running a compute plan, multiples docker images were created with different names and not removed due to a simple rule: if it's a compute plan do not remove the image.
The fix make sure that docker images depends on algo key rather than tuple key.

fix docker image task name

---

backend/backend/settings/prod.py
backend/events/apps.py

Fix #109 before a substra-backend app split :)
To reproduce and see the handle of the channel event hub connection you can launch a substra network and kill the orderer, you will see the #109 issue.
When the orderer goes up, this PR allows the channel event hub to reconnect

Add event hub reconnect strategy + log in production

---

backend/backend/celery.py
backend/backend/settings/common.py
backend/backend/settings/dev.py
backend/backend/settings/prod.py
charts/substra-backend/templates/deployment-celerybeat.yaml
charts/substra-backend/values.yaml
docker/start.py

When celerybeat sends periodic tasks, it try to push the celery result to django-db. It will fail as celerybeat is not connected to the posgresql db.
As we do not need this database, we could avoid, for the celerybeat to send the result of celery task.
Moreover, I added a setting to setup the frequency of the periodic task (in case of event hub failure we can increase frequency).

Fix issue with celerybeat periodic tasks

---

backend/substrapp/tasks/tasks.py

Since there are no more predictions for traintuples and composite_traintuples, we should only mount the pred volume in case of testtuple. 
I tested this change against https://github.com/SubstraFoundation/substra-tools/pull/24

Only mount pred volume for testtuples

---

backend/substrapp/tests/assets.py
backend/substrapp/tests/views/tests_views_algo.py
backend/substrapp/tests/views/tests_views_compositealgo.py
backend/substrapp/tests/views/tests_views_datamanager.py
backend/substrapp/tests/views/tests_views_model.py
backend/substrapp/tests/views/tests_views_objective.py
backend/substrapp/views/filters_utils.py

Fix #120 
All tuples previously had an objective attached to then when created so that they could have a training score. Now that this has disappeared, only testtuples have objective attached.
As a result, only models that have testtuples can be filtered by objective.

Fix model filtering

---

backend/backend/settings/common.py
backend/backend/settings/dev.py
backend/backend/settings/prod.py
backend/substrapp/ledger_utils.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tasks/utils.py
backend/substrapp/utils.py
backend/substrapp/views/datasample.py
backend/substrapp/views/filters_utils.py
backend/substrapp/views/model.py

- add a log for each request done to the ledger
- no more calls to root logger (`logging.info(...)`), use a module logger instead: it will allow better logging configuration and tuning
- review dev settings for log configuration:
- remove mail and file handlers: they are not used in dev mode
- add substrapp logger
- set custom configuration for external library when needed (hfc,
celery, ...)
- ensure all emitted logs to the console have the same formatters (in all services)
- review prod settings for log configuration
- remove unused handlers and formatters
- update default formatter
- add settings/env variables to:
- disable SQL query logs
- disable worker printing tuple workerspace

Review logging (dev and prod settings)

---

backend/substrapp/views/aggregatealgo.py
backend/substrapp/views/algo.py
backend/substrapp/views/compositealgo.py
backend/substrapp/views/datamanager.py
backend/substrapp/views/objective.py

So it appears `description` may be a semi-reserved keyword in DRF.
Trying to access any "description" route made the server break without even entering the view. Everything in the stacktrace was internal to django and DRF.

Fix description route

---

backend/substrapp/management/commands/createdataset.py
backend/substrapp/views/datamanager.py

The backend was in the middle of nowhere to set the objective key of a dataset:
- accepting  'objective_keys' from the request and sending this field to the ledger serializer
- ledger serializer looking for an 'objective_key' field
As a dataset can be linked with only one objective, the correct field is 'objective_key'.
Companion PRs:
- [substra](https://github.com/SubstraFoundation/substra/pull/94)
- [tests](https://github.com/SubstraFoundation/substra-tests/pull/66)

Fix: dataset can be linked with only one objective

---

backend/backend/views.py
backend/substrapp/tests/views/test_views_authentication.py

The route /api-auth-token was behind our authentication backends. Which meant that requesting the route with an invalid token but a valid user/login (which might happen if the token is expired for example, or if you're using a token from a different node) returned a 400 each time.
This PR removes the authentication backend checks and makes sure that only the password/login are considered.

Do not authenticate user for /api-auth-token route

---

charts/substra-backend/requirements.lock
charts/substra-backend/requirements.yaml

StatefulSet in apps/v1beta2 is deprecated in kubernetes 1.16 and we should now use apps/v1.
These versions of rabbitmq and postgresql charts are compatible with the kubernetes 1.16 API.
This modification is backward compatible with kubernetes 1.15.

Bump rabbitmq and postgresql charts

---

backend/substrapp/ledger.py
backend/substrapp/serializers/ledger/computeplan/serializer.py
backend/substrapp/tests/views/tests_views_computeplan.py
backend/substrapp/views/computeplan.py

Update compute plan.
- new route `/compute_plan/<compute_plan_id>/update_ledger`
Companion PRs:
- CLI/SDK: https://github.com/SubstraFoundation/substra/pull/104
- tests: https://github.com/SubstraFoundation/substra-tests/pull/69
- chaincode: https://github.com/SubstraFoundation/substra-chaincode/pull/89
Testing procedure:
- run the compute_plan example from the titanic example
- use the update_compute_plan command from the sdk to add a testtuple to one of the existing traintuples. This testtuple should have the same compute_plan_id as the compute plan and the result of the get compute plan should list the testtuple.

Update compute plan

---

backend/substrapp/ledger_utils.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tests/query/tests_query_compositetraintuple.py
backend/substrapp/tests/views/tests_utils.py
backend/substrapp/views/model.py
backend/substrapp/views/utils.py

This PR depends on https://github.com/SubstraFoundation/substra-chaincode/pull/79
Companion PR in tests: https://github.com/SubstraFoundation/substra-tests/pull/70
- Adds a new check on permission preventing model downloads from nodes who don't have permissions
- Relies on a new chaincode smartContract to retrieve the permissions associated with a model.
To reproduce the original issue:
- run `test_permissions_denied_model_process` from substra-tests
- get the model url from the traintuple whose algo is `xxxxxxx_test_permissions_denied_model_process - Algo 1` This model should only be processable by MyOrg2MSP.
- curl the URL using the node1 to node2 credentials: `MyOrg1MSP:nodeSecret2w1`
You should get a 200 without the fix and a 403 with the fix.

Fix model download permissions

---

backend/backend/celery.py
backend/substrapp/tasks/tasks.py

this has not been done when introducing composite and aggregate tuples.
⚠️ has not yet been tested

fix celery scheduler

---

backend/substrapp/views/model.py
backend/substrapp/views/utils.py

1. Only gzip models, to be conservative. We could decide to gzip more routes (or all the routes) in the future.
2. The middleware takes care of not gzipping small payloads (<200b), not gzipping the payload if the the client doesn't support it, not gzipping if the response is already compressed, etc
3. The client (`requests.get`) already adds `Accept-Encoding: gzip,deflate`, and decompresses accordingly if the response has `Content-Encoding: gzip`. So we don't need to do anything client-side.
You can check that the response is actually encoded by doing a HTTP request manually with curl (and adding `Accept-Encoding: gzip`), or by adding this to `utils.py`
```python
enc = response.headers.get('Content-Encoding', 'unknown')
logger.info(f'Response encoding: {enc}')
```

gzip models during download

---

backend/requirements.txt
backend/substrapp/ledger_utils.py
backend/substrapp/tasks/utils.py

Fix #77
- Use close grpc channels function from fabric-sdk-py
- Use retry grpc strategy in chaincode invoke
- disable raise exception in case of unavailable broker
- Fix celery image default in case of unset env variable

Update fabric-sdk and set up new features

---

skaffold.yaml

With this little change you can now launch the backend with the prod settings with:
```sh
skaffold dev -p prod
```
You can make sure this works by executing the command above, opening a shell in one of the server or worker containers and running `printenv | grep prod` in it.

Add prod profile to skaffold

---

backend/substrapp/serializers/datasample.py
backend/substrapp/serializers/utils.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tests/tests_misc.py
backend/substrapp/utils.py

Filenames should be validated when storing asset to prevent from path/directory traversal.
Companion PR :  https://github.com/SubstraFoundation/substra/pull/151

Prevent from path traversal when saving models or extracting archives

---

backend/backend/settings/deps/restframework.py
backend/backend/views.py
backend/libs/user_login_throttle.py
backend/users/views/user.py

This PR adds throttling to:
* all endpoints for anonymous users (limited to 60calls/minute globally)
* the 2 login endpoints (for both sdk and frontend) for anonymous and logged in users alike.
This PR has been tested against substra-tests, all e2e tests work normally (as expected).
In order to make sure the throttling works as expected, here is a test script:
```python
import requests
import time
credentials = {'username': 'node-1', 'password': 'p@$swr0d44'}
def req(url, token=None, data=None):
url = f'http://substra-backend.node-1.com{url}'
headers = {
'Accept': 'application/json;version=0.0'
}
if token:
headers['Authorization'] = f"Token {token}"
return requests.post(url, data=data, headers=headers)
def test_throttle(url, token=None):
for i in range(60):
r = req(url, token)
assert …
```

Throttling

---

backend/backend/settings/deps/restframework.py
backend/backend/settings/dev.py
backend/backend/urls.py
backend/substrapp/views/utils.py

This has been tested against substra-tests in dev mode with success.
I tried running it against skaffold modified as follows to emulate a prod mode. I only had one test failing: test_execution_retry_on_fail. But it looks like it is a known bug not linked to these changes: https://github.com/SubstraFoundation/substra-tests/issues/48
```diff
diff --git a/skaffold.yaml b/skaffold.yaml
index d79ccb9d..6951f670 100644
--- a/skaffold.yaml
+++ b/skaffold.yaml
@@ -39,7 +39,7 @@ deploy:
secrets:
fabricConfigmap: network-org-1-hlf-k8s-fabric
backend:
-            settings: dev
+            settings: prod
defaultDomain: http://substra-backend.node-1.com
ingress:
enabled: true
@@ -81,7 +81,7 @@ deploy:
secrets:
fabricConfigmap: network-org-2-hlf-k8s-fabric
backend:
-            settings: dev
+ …
```

Enable browsable API in dev mode only

---

backend/backend/settings/common.py
backend/substrapp/tasks/tasks.py

Adds a new environment variable, `ENABLE_REMOVE_LOCAL_CP_FOLDERS `, which defaults to True that drives whether local volumes for compute plan will be removed or not.
To test, you can add the following test to substra-tests and run it.
* If you have the option set to true, the test will fail on the second traintuple
* if you have the option set to false, the test will succeed
```python
def test_remove_local_folder(global_execution_env):
to_replace = """
tools.algo.execute(TestAlgo())"""
write_to_local_folder = """
test_path = "/sandbox/local/foo"
with open(test_path, 'w') as f:
f.write('foo')
tools.algo.execute(TestAlgo())
"""
read_from_local_folder = """
test_path = "/sandbox/local/foo"
with open(test_path, 'r') as f:
f.read()
tools.algo.execute(TestAlgo())
"""
factory, initial_assets, …
```

Add option to enable/disable folder deletion at end of compute plan

---

charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-worker.yaml
charts/substra-backend/templates/rbac.yaml
charts/substra-backend/values.yaml

Add ServiceAccount for the worker making it able to list, retrieve and create secrets in his workspace.
This PR could be adapted to add different Kubernetes ressources the worker would need to access.

Add service account for worker

---

backend/substrapp/tasks/tasks.py
backend/substrapp/tests/tests_tasks.py
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker.yaml
charts/substra-backend/templates/storage.yaml
charts/substra-backend/values.yaml
docker/start.py
skaffold.yaml

For the mission kubernetize hlf we improve substrabac volume handling to allow only read-write-once on it.
It changes the `get_objective` workflow (we do not register the objective in the local db anymore)
Companion PR https://github.com/SubstraFoundation/substra-tests/pull/82

Update volume binding for read write once

---

charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker.yaml

Without this env variable the requests python module will not use the private CA as by default this module use the root CA bundle provided by the module [certifi](https://pypi.org/project/certifi/) and not the OS trusted root CA bundle.

Fix the fact that the requests module does not use the system CA bundle

---

backend/backend/settings/deps/restframework.py

Increase throttle rates from 60 to 120 to avoid potential api call http 429 issue during `substra-tests` test suite.

Increase throttle rates from 60 to 120

---

backend/backend/settings/dev.py
backend/backend/settings/prod.py

Fixes https://github.com/SubstraFoundation/substra-backend/issues/214
This PR adds the following logs:
- Task reception/start
```
Received task: substrapp.tasks.tasks.prepare_tuple[974631f5db396abcfb51776042e6ef7be32212adf8983114215cbdb1ed9c611d  
Received task: substrapp.tasks.tasks.compute_task[ccda03f7-3234-4f2d-af4f-c66f00c882fa  
```
- Task retry + exception causing the retry
```
Task substrapp.tasks.tasks.compute_task[ccda03f7-3234-4f2d-af4f-c66f00c882fa retry: Retry in 0s: ContainerError('Command \'train\' in image \'substra/algo_a709ebd2\' returned non-zero exit status 1: b\'substratools.utils - [Traceback]
```
- Task success
```
Task substrapp.tasks.tasks.prepare_tuple[974631f5db396abcfb51776042e6ef7be32212adf8983114215cbdb1ed9c611d succeeded in 0.11992721299975528s: None
Task …
```

Don't swallow celery logs

---

charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-worker.yaml

This way we can force the worker to be scheduled on the same node as the backend in a multi node setup.
This is required in a multi node environment because the backend and worker needs to share files using the host filesystem.
This PR has not been tested against a local environment.

Add pod affinity to backend worker

---

skaffold.yaml

Fixes https://github.com/SubstraFoundation/substra-backend/issues/223
Note: the prefix `http://` is necessary because of the url validation on the chaincode side ([example](https://github.com/SubstraFoundation/substra-chaincode/blob/4744da151530e8ef4b3175690eefd37db5d9b315/chaincode/input.go#L36))
﻿

Local setup (skaffold): don't assume host DNS propagation

---

backend/backend/settings/deps/restframework.py
backend/libs/json_multipart_parser.py
backend/substrapp/serializers/ledger/aggregatetuple/serializer.py
backend/substrapp/serializers/ledger/compositetraintuple/serializer.py
backend/substrapp/serializers/ledger/computeplan/serializer.py
backend/substrapp/serializers/ledger/datamanager/serializer.py
backend/substrapp/serializers/ledger/objective/serializer.py
backend/substrapp/serializers/ledger/testtuple/serializer.py
backend/substrapp/serializers/ledger/traintuple/serializer.py
backend/substrapp/tests/query/tests_query_algo.py
backend/substrapp/tests/query/tests_query_compositetraintuple.py
backend/substrapp/tests/query/tests_query_datamanager.py
backend/substrapp/tests/query/tests_query_datasample.py
backend/substrapp/tests/query/tests_query_objective.py
backend/substrapp/tests/query/tests_query_tuples.py
backend/substrapp/tests/views/tests_views_algo.py
backend/substrapp/tests/views/tests_views_compositealgo.py
backend/substrapp/tests/views/tests_views_datasample.py
backend/substrapp/tests/views/tests_views_objective.py
backend/substrapp/views/aggregatealgo.py
backend/substrapp/views/aggregatetuple.py
backend/substrapp/views/algo.py
backend/substrapp/views/compositealgo.py
backend/substrapp/views/compositetraintuple.py
backend/substrapp/views/datamanager.py
backend/substrapp/views/datasample.py
backend/substrapp/views/objective.py
backend/substrapp/views/testtuple.py
backend/substrapp/views/traintuple.py

Companion PR: https://github.com/SubstraFoundation/substra/pull/162
Until now, when sending files alongside data in a request, the data was encoded as form data. This prevented us from sending complex data structures, and for example forced us to send these permissions:
```json
{
"public": True,
"authorized_ids": []
}
```
as:
```
permissions_public = True,
permissions_authorized_ids = True
```
And then forced us to parse the upload to recreate the dict on the server side before passing it to the serializer.
In order to send files and data in one call, we can serialize all data in json format and pass it as the value of a "json" formdata. 
A new request parser is then written that inherits from the DRF's multipart parser that automatically handles the deserialization of the "json" …

Allow receiving data as json in multipart requests

---

charts/substra-backend/Chart.yaml

Follow up to https://github.com/SubstraFoundation/substra-backend/pull/227
We forgot to update the chart version﻿

Fix chart version

---

backend/backend/views.py
backend/substrapp/tests/views/test_views_authentication.py

- Create a new token for each login (remove the old one)
- Token validity is still 24h

Update api token strategy

---

backend/events/apps.py
backend/substrapp/serializers/__init__.py
backend/substrapp/serializers/model.py
backend/substrapp/tasks/utils.py
backend/substrapp/tests/tests_misc.py
backend/substrapp/tests/tests_password_validation.py
backend/substrapp/tests/views/test_views_authentication.py
backend/substrapp/views/datasample.py
backend/substrapp/views/model.py

Related to #160 
Companion PR : https://github.com/SubstraFoundation/substra-frontend/pull/43
Merge retrieve and details view
This PR doesn't change the `model/<model_hash>/file` path because:
- this path is only use between node
- the ledger call is different that other path : `queryModelPermissions ` and not `queryModelDetails`
- model file are registered in the db (and the ledger via storage address) with the hash of the model. To change it, we will need to change the chaincode.

Streamline Model view

---

backend/substrapp/serializers/ledger/compositetraintuple/serializer.py
backend/substrapp/serializers/ledger/utils.py

Fixes #148 
Companion PRs:
* ~substra-chaincode~ 
* [substra-tests](https://github.com/SubstraFoundation/substra-tests/pull/92)
* ~[substra](https://github.com/SubstraFoundation/substra/pull/148)~

Remove public key from trunk model permissions

---

charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-server.yaml

In production scenarios, incoming requests can take a long time to be processed (due to the blockchain nature of the application).
Reduce the chances of broken pipes by increasing the maximum allowed duration for client HTTP connections.

Prod: increase UWSGI timeouts

---

backend/substrapp/tasks/k8s_backend.py
charts/substra-backend/templates/deployment-worker.yaml

Adding this the compute pod should always get scheduled on the same node as the substra worker pod.

Add pod affinity to the worker task

---

backend/substrapp/tasks/tasks.py

Currently, generated tar.gz files can only be uploaded at the root of an s3 bucket.
This PR adds support for `.tar.gz` upload into s3 prefixes, which are the s3 equivalent of subfolders.

Add prefix functionality for S3 bucket upload

---

backend/backend/settings/deps/cors.py
skaffold.yaml

Disable CORS_ALLOW_CREDENTIALS
But for front-end you need to set it to true to allow it to login in the backend !

Disable CORS_ALLOW_CREDENTIALS by default

---

charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-worker.yaml
charts/substra-backend/values.yaml

Sometimes when running high memory workers it is not possible to perform a rolling update as there is not enough memory in the cluster to satisfy the requests of two worker.
Making this a value we can set gives us the possibility to choose a deployment strategy `Recreate` which will first delete the old worker and then recreate a new worker.
Documentation: [k8s-deployment-strategy](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#deploymentstrategy-v1-apps)

Add worker update strategy as a value

---

backend/substrapp/tasks/k8s_backend.py

With this common label we should be able to identify all compute pods started by the backend in a unique way. Making deletion of these pods easier if they fail.

Add a common label to compute pods

---

backend/substrapp/serializers/ledger/computeplan/serializer.py

:link: **Related Pull Requests :**
• [substra](https://github.com/SubstraFoundation/substra/pull/189)
• [substra-tests](https://github.com/SubstraFoundation/substra-tests/pull/112)
• [substra-chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/121)
This PR aims to add a metadata field to the compute plan asset.

Add metadata to compute plan

---

charts/substra-backend/values.schema.json

Add a simple validation schema for the Helm values, this validation schema enforce prod settings constraints on the user values.
You can check your value.yaml file is valid running `helm lint --values <values_file>`.
resolve #262 
```yaml
users:
- name: user-1
secret: "111111111111s111111111111111111111111111111ze"
- name: user-2
secret: 456846881654841dsfsdf8sdf4sdf6
```
> Valid ✅ 
```yaml
users:
- name: user-1
secret: "111111111111111111111111111111111111111111"
```
> Error ❌  => password should contain atleast one letter
```yaml
users:
- name: user-1
secret: "111111111111s111111111111111111111111111111ze"
- name: user-2
secret: "456846881654841dsfsdf8sdf4sdf6"
- name: user-2
secret: "456846881654841dsfsdf8sdf4sdf6"
```
> Error ❌ => Items must be unique
There is currently no way to …

Add validation schema for helm values

---

charts/substra-backend/values.schema.json

The Helm validation schema was breaking skaffold deployment as the values in dev mode were not compliant with the lint.
Now the validation schema is conditional and verify password length only if you are using the `prod` settings for the backend value: 
```yaml
backend:
settings: prod
```
```yaml
backend:
settings: dev
users:
- name: "node-2"
secret: "p@$swr0d45"
```
> Valid ✅ 
```yaml
backend:
settings: prod
users:
- name: "node-2"
secret: "p@$swr0d45defgtyhfedcd"
```
> Valid ✅ 
```yaml
backend:
settings: prod
users:
- name: "node-2"
secret: "p@$swr0d45"
```
> Invalid ❌  : password should be 20 char in prod mode

Fix validation schema

---

charts/substra-backend/Chart.yaml
charts/substra-backend/values.yaml

Use pvc for docker registry data storage instead of emptyDir that may create issue if storage on node is greater than 80% (pod eviction by kubernetes)

Melloddy docker registry pvc

---

backend/substrapp/serializers/ledger/computeplan/serializer.py

Fixes #309 
It also fixes a bug: authorized_ids were never correctly for out trunk model permissions when creating composite traintuples via compute plans.
Related test: https://github.com/SubstraFoundation/substra-tests/pull/135

Use private permissions for CP compositetuple

---

backend/substrapp/tasks/tasks.py

In compute plans, the metrics image is typically the same for multiple ranks.
This PR makes it so:
- the metrics image name is built from the objective hash and not the tuple hash.
- the metrics image is not deleted after use (compute plans only)
As a result, if a compute plan uses the same objective for multiple iterations, the same metrics image will be reused without the need to rebuild it for every testtuple.
-- 
Note that this code is already merged in melloddy https://github.com/SubstraFoundation/substra-backend/pull/267. The goal of this PR is to reflect the changes in master.

Reuse metrics image in compute plans

---

charts/substra-backend/Chart.yaml
charts/substra-backend/values.yaml

Use pvc for docker registry data storage instead of emptyDir that may create issue if storage on node is greater than 80% (pod eviction by kubernetes)

Use pvc for docker registry data.

---

backend/substrapp/tasks/tasks.py

This optimization already existed for traintuples, composite traintuples and aggregate tuples.
This PR adds the same optimization for testtuples.

worker: don't process testtuples tasks unless they are "todo"

---

backend/substrapp/tests/assets.py
backend/substrapp/tests/common.py
backend/substrapp/tests/generate_assets.py
backend/substrapp/tests/query/tests_query_algo.py
backend/substrapp/tests/query/tests_query_compositetraintuple.py
backend/substrapp/tests/query/tests_query_datamanager.py
backend/substrapp/tests/query/tests_query_datasample.py
backend/substrapp/tests/query/tests_query_objective.py
backend/substrapp/tests/query/tests_query_tuples.py
backend/substrapp/tests/views/tests_views_algo.py
backend/substrapp/tests/views/tests_views_compositealgo.py
backend/substrapp/tests/views/tests_views_datamanager.py
backend/substrapp/tests/views/tests_views_datasample.py
backend/substrapp/tests/views/tests_views_model.py
backend/substrapp/tests/views/tests_views_objective.py
backend/substrapp/tests/views/tests_views_tuples.py
backend/substrapp/views/aggregatealgo.py
backend/substrapp/views/aggregatetuple.py
backend/substrapp/views/algo.py
backend/substrapp/views/compositealgo.py
backend/substrapp/views/compositetraintuple.py
backend/substrapp/views/datamanager.py
backend/substrapp/views/datasample.py
backend/substrapp/views/filters_utils.py
backend/substrapp/views/objective.py
backend/substrapp/views/testtuple.py
backend/substrapp/views/traintuple.py
backend/substrapp/views/utils.py

The goal of this multi-repo PRs is to make sure that all the asset creation endpoints returns only the "key" of the asset. 
Indeed, currently `create` and 'get' an asset return, respectively, `pkhash` and `key`. As `pkhash` is only a substra-backend concept, we need to move from `pkhash` to `key` when dealing with substra cli/sdk and frontend.
Consequently, when client create a new asset, the substra-backend will now only return the `key` of the created asset.
There is an exception for compute plan which need to be returned in its complete form because client need to get the ID_to_key mapping and it’s returned only when client create this asset.
The client will take care of doing an extra GET in order to retrieve the complete asset.
PRs : …

Return key instead of pkhash

---

.travis.yml
skaffold.yaml

As we will only support helm3 going forward we should use Helm3 for the CI checks.

Switch Travis to Helm3

---

skaffold.yaml

When launching the frontend locally through yarn, it is served at port 3000 (dev mode) or 3001 (prod mode). It was previously rejected by the backend because not in the CORS whitelist.

Add dev frontend to list of CORS whitelist

---

backend/events/apps.py
backend/node/tests/views/tests_views_node.py
backend/node/views/node.py
backend/substrapp/ledger_utils.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tests/assets.py
backend/substrapp/tests/common.py
backend/substrapp/tests/query/tests_query_compositetraintuple.py
backend/substrapp/tests/tests_misc.py
backend/substrapp/tests/tests_tasks.py
backend/substrapp/tests/views/tests_utils.py
backend/substrapp/tests/views/tests_views_algo.py
backend/substrapp/tests/views/tests_views_compositealgo.py
backend/substrapp/tests/views/tests_views_compositetraintuples.py
backend/substrapp/tests/views/tests_views_computeplan.py
backend/substrapp/tests/views/tests_views_datamanager.py
backend/substrapp/tests/views/tests_views_model.py
backend/substrapp/tests/views/tests_views_objective.py
backend/substrapp/tests/views/tests_views_tuples.py
backend/substrapp/views/aggregatealgo.py
backend/substrapp/views/algo.py
backend/substrapp/views/compositealgo.py
backend/substrapp/views/computeplan.py
backend/substrapp/views/datamanager.py
backend/substrapp/views/filters_utils.py
backend/substrapp/views/model.py
backend/substrapp/views/objective.py
backend/substrapp/views/utils.py

The backend responses should be more consistent. The goal of this PR is to make sure that all inputs fields and response fields of backend endpoints are in snake_case format.
PRs:
https://github.com/SubstraFoundation/substra-backend/pull/315
https://github.com/SubstraFoundation/substra/pull/222
https://github.com/SubstraFoundation/substra-tests/pull/142

Switch output from camel case to snake case

---

docker/celerybeat/Dockerfile
docker/celeryworker/Dockerfile

The CUDA image isn't necessary in the worker anymore.
Use the python image to improve cache reuse across generated docker images (substra-backend / celeryworker / celerybeat)

worker: don't use CUDA as base image

---

backend/backend/settings/deps/ledger.py
backend/events/apps.py
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/configmap-server.yaml
charts/substra-backend/values.yaml

Add a keepalive (120 sec) to all the GRPC links﻿.
This prevents links from being closed by network software/equipment because of inactivity.

GRPC: add keepalive (120 sec)

---

skaffold.yaml

Some users have reported that 5 minutes is not enough time on their machines for the application to stabilize.﻿

Bump status check deadline

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/README.md
charts/substra-backend/templates/job-registry-prepopulate.yaml
charts/substra-backend/values.yaml

This chart parameter has been mistakenly deleted in https://github.com/SubstraFoundation/substra-backend/pull/326
We do need this parameter for melloddy deploys.﻿

Revive sourceRegistry

---

backend/node-register/apps.py
charts/substra-backend/templates/configmap-server.yaml

This PR makes the startup faster and more verbose in case of initialization error (e.g. peer not in channel yet)
1. If an exception occurs when calling the ledger in the application initialization (register-node), do not crash the app. 
Instead, retry the ledger call indefinitely. This is faster than crashing the pod and waiting for it to restart. Note that kubernetes will still crash the pod if the readiness probe fails (i.e. initialization repeatedly fails for > 30 secs or so)
2. With the `log-master=true`﻿ option, no logs are output until the app initialization is complete or the pod is crashed. In other words, if the app initialization takes a long time, we can't see the logs until either the initialization finally succeeds, or the container is stopped by kubernetes.
...wait... …

Faster startup in case of initialization error + more verbose logs

---

backend/substrapp/tasks/tasks.py
backend/substrapp/tests/tests_tasks.py
charts/substra-backend/values.yaml
values/backend-org-1.yaml
values/backend-org-2.yaml

:warning: In order for this PR to be merged, https://github.com/SubstraFoundation/substra-tools/pull/43 has to be merged first and the 0.7.0 release done.
With this change, the relative order of data samples is added to the command executed by the algo container during training.

Data samples order

---

backend/substrapp/ledger/api.py
backend/substrapp/ledger/exceptions.py
backend/substrapp/tests/tests_misc.py

Add LedgerNotFound exception in retry `update_ledger`
A org may try to launch a traintuple (i.e. `log_start_tuple` via an invoke). During this procedure, the transaction is endorsed by each peer (Another org here).
But, even if the first org had already the block with the traintuple metadata, the second org may not have it at this moment so the endorsement request will fail with a `no asset for key` error.
In order to fix this potential issue, we can use the retry mecanism and add LedgerNotFound exception)

Add LedgerNotFound exception in retry update_ledger

---

charts/substra-backend/requirements.lock
charts/substra-backend/requirements.yaml

https://kubernetes-charts.storage.googleapis.com/ is now unavailable. Switch to charts.helm.sh

helm: don't reference https://kubernetes-charts.storage.googleapis.com/

---

backend/requirements.txt

This fixes the [currently failing docker build](https://hub.docker.com/repository/registry-1.docker.io/substrafoundation/substra-backend/builds/cb6f01cc-88eb-4c89-b564-8c85410c0e17)
```
ERROR: Cannot install -r requirements.txt (line 19) and requests==2.24.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested requests==2.24.0
fabric-sdk-py 1.0.0 depends on requests==2.20.0
```
See also: https://github.com/hyperledger/fabric-sdk-py/pull/125

relax version requirement on requests package

---

backend/libs/health_check_middleware.py
backend/substrapp/ledger/connection.py
charts/substra-backend/README.md
charts/substra-backend/values.yaml
values/backend-org-1.yaml
values/backend-org-2.yaml

**TL;DR:** Channels can be marked as "restricted" (also called "solo"). Restricted channels can only have one member, else the backend will (deliberately) crash.
---
A channel is configured as restricted if either of these conditions are true in the helm values file:
- the `restricted` field of the channel is set to true
- the name of the channel starts with `solo-`
*Note: In the rest of this doc, "misconfigured" refers to a solo channel with more than one member.*
2 protections are implemented to prevent any operation on a misconfigured solo channel.
Throw an exception when trying to operate on a misconfigured solo channel
`get_hfc(channel_name)` will 
1. check if `channel_name` refers to a solo channel
2. check the channel's discovery results
3. if the channel has more than one member, …

Introduce restricted channels

---

backend/substrapp/tasks/tasks.py
backend/substrapp/tasks/utils.py

Django ORM connections are not fork safe. We need to close them all in celery task to force Process open new connection once launched
Fix #353 
None
Update outgoing node values for org-1:
​
```yaml
outgoingNodes:
- { name: MyOrg1MSP, secret: selfSecret1 }
- { name: MyOrg2MSP, secret: nodeSecret2w1 }
- { name: MyOrg3MSP, secret: nodeSecret3w1 }
- { name: MyOrg4MSP, secret: nodeSecret4w1 }
- { name: MyOrg5MSP, secret: nodeSecret5w1 }
- { name: MyOrg6MSP, secret: nodeSecret6w1 }
- { name: MyOrg7MSP, secret: nodeSecret7w1 }
- { name: MyOrg8MSP, secret: nodeSecret8w1 }
- { name: MyOrg9MSP, secret: nodeSecret9w1 }
- { name: MyOrg10MSP, secret: nodeSecret10w1 }
- { name: MyOrg12MSP, secret: nodeSecret12w1 }
- { name: MyOrg13MSP, secret: nodeSecret13w1 }
- { name: MyOrg14MSP, secret: …
```

Close db connection before launching Process under celery task.

---

backend/substrapp/ledger/api.py
backend/substrapp/tests/tests_misc.py

The aim of this PR is to handle chaincode pagination for query[Asset]s.
None
https://github.com/SubstraFoundation/substra-chaincode/pull/131
Launch e2e tests, no regression should appear.
None
None

Handle chaincode pagination

---

values/backend-org-1.yaml
values/backend-org-2.yaml

Django checks are failing because of the trailing slash: CORS
whitelist items should not contain path.
django-cors-headers [explicitly check](https://github.com/adamchainz/django-cors-headers/blob/3.2.1/src/corsheaders/checks.py#L99) that there is no path.

Remove trailing slash in CORS whitelist

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/add-account-operator.yaml
charts/substra-backend/templates/configmap-add-account.yaml
charts/substra-backend/templates/configmap-events.yaml
charts/substra-backend/templates/configmap-ledger.yaml
charts/substra-backend/templates/configmap-private-ca.yaml
charts/substra-backend/templates/configmap-server-uwsgi.yaml
charts/substra-backend/templates/deployment-celerybeat.yaml
charts/substra-backend/templates/deployment-events.yaml
charts/substra-backend/templates/deployment-scheduler.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker.yaml
charts/substra-backend/templates/ingress.yaml
charts/substra-backend/templates/job-image-builder-warmer.yaml
charts/substra-backend/templates/job-registry-prepopulate.yaml
charts/substra-backend/templates/network-task-deny-all.yaml
charts/substra-backend/templates/pod-security-policy.yaml
charts/substra-backend/templates/rbac.yaml
charts/substra-backend/templates/secret-pull.yaml
charts/substra-backend/templates/service-server.yaml
charts/substra-backend/templates/storage.yaml

This PR introduces a template for k8s labels in the helm chart. 
I updated all the old labels to use this new template for common labels and added labels to objects that were not labeled before.
The common labels includes:
- `helm.sh/chart`
- `app.kubernetes.io/managed-by`
- `app.kubernetes.io/part-of`
- `app.kubernetes.io/instance`
I hesitated to make `app.kubernetes.io/name` part of the common labels as it is all a single app and replace it in the code by `app.kubernetes/component` as we use it as a label selector for substra components deployments. Let me know if this is something we would like.
The goal here is to simplify label usage from the point of view of a chart maintainer avoiding drift in the labels as we could have before. You also have only to write one line to add all the …

Refactor kubernetes labels

---

.github/workflows/helm.yml
charts/substra-backend/README.md

Update git ref to target a branch instead of a tag.
I also added a small change to the chart (removed an empty line) just to trigger a publication of the chart that was not published.
This is preventing the CI from publishing the helm chart as the current ref is a master tag and not a branch.
N/A
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

Fix branch ref

---

backend/requirements.txt

This PR contains several dependencies update 📦 
- ✂️ each commit is independent: it's easy to dismiss an update considered _risky_
- ✅ each commit has been checked against the substra test suite
- 🦺 only minor/patch versions were updated, some major updates are available but should be handled independently

Minor updates of dependencies

---

backend/backend/settings/common.py
backend/requirements.txt

The removal of the swagger generation has been mostly done in #196
The dependency was unused since, this commit removes it.

[deps] remove django-rest-swagger

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker.yaml
charts/substra-backend/templates/storage.yaml
charts/substra-backend/values.yaml

Flatten the array of volumes under the key `persistence.volumes`.
This result in the same yaml manifest output by helm.
This change does not reduce our possibilities as it would never have been possible to write a `.name` property with a value like `Awesome volume`.  The value is used in object name and that field that must mach the object name policy of kubernetes.
With this modification a user is able to change the size of one of the volumes without redefining the whole array of values.
This prevent from a typo or mistakes in the other fields of these values when you only want to redefine one of them.
Previously you had to write this in your value file to redefine `aggregatealgos` volume size from `10Gi` to `255Gi`
```yaml
persistence:
volumes:
- name: algos
size: "10Gi"
readOnly: …
```

Flatten volumes values

---

backend/requirements.txt

Bump djangorestframework-simplejwt version to be compatible with PyJWT 2.0.0

Bump djangorestframework-simplejwt to 4.6.0

---

.github/workflows/python.yml

Set CI python version to `3.6`.
The python version in the CI was not matching the python version in the [Dockerfile](https://github.com/SubstraFoundation/substra-backend/blob/f8870a353d1d241bcf753a21147583a3d8a04651/docker/substra-backend/Dockerfile#L1), this was making the CI unreliable to validate modifications.
We noticed this issue after the merge of #366 where the CI was running okay but the DockerHub build was failing.
You can look at the logs of the checks tab.
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

Fix CI python version

---

README.md

Rebuilding some images now leads to broken backend. While this has been fixed by #367, previous releases cannot be rebuilt correctly. However, images in [registry](https://hub.docker.com/r/substrafoundation/substra-backend) are fine, so this only really impacts local usage of previous tags.
In order to run a previous version locally, instead of rebuilding the image, this PR introduce a new skaffold config file to run an arbitrary backend version.
Skaffold allows to deploy without building (`deploy` command), so let's just leverage that.
Here is the snippet added to the readme:
```bash
SUBSTRA_BACKEND_VERSION=0.1.6
git checkout $SUBSTRA_BACKEND_VERSION
docker pull substrafoundation/substra-backend:$SUBSTRA_BACKEND_VERSION
skaffold deploy --images …
```

[doc] prefered way to deploy with images from repo

---

backend/requirements.txt

Fix the grpcio version until the issue is fixed upstream.
Segmentation faults have been observed in some deployments (testnet) on the backend-server pod
```
!!! uWSGI process 306 got Segmentation Fault !!!
*** backtrace of 306 ***
uwsgi(uwsgi_backtrace+0x2a) [0x55909c38e34a]
uwsgi(uwsgi_segfault+0x23) [0x55909c38e703]
/lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7f0f9af26840]
/usr/local/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so(+0x2a7735) [0x7f0f97999735]
/usr/local/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so(+0x29e7d2) [0x7f0f979907d2]
/usr/local/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so(+0x29f649) [0x7f0f97991649]
/usr/local/lib/python3.6/site-packages/grpc/_cython/cygrpc.cpyth …
```

fix the grpcio version to 1.30.0

---

backend/backend/settings/common.py
backend/backend/settings/deps/restframework.py
backend/backend/urls.py
backend/requirements.txt

This adds 3 new routes:
- /schema/ exposing the openapi spec
- /schema/swagger-ui/ to browse the spec with the swagger UI
- /schema/redoc/ to browse the spec with the redoc UI
A similar feature previously existed, provided by django-rest-swagger
but the repository has been archived and the author recommended
drf-yasg. On the documentation page of drf-yasg, the author mentions
that drf-yasg won't support openapi 3.0 and recommend to use
drf-spectacular to expose an openapi 3.0 spec.
That's why I chose drf-spectacular, which works the same way than
django-rest-framework and is BSD licensed.
<details>
<summary>Here is the swagger view ⬇️ </summary>
</details>
<details>
<summary>And the redoc one ⬇️ </summary>
</details>
Here is the generated schema: …

[doc] expose generated openapi spec

---

backend/substrapp/tasks/k8s_backend.py
backend/substrapp/tasks/tasks.py
backend/substrapp/tasks/utils.py
backend/substrapp/tests/views/tests_local_folder.py
backend/substrapp/utils.py

The aim of this PR is to be able to retry composite traintuple in a deterministic way. Indeed, as we mount the local folder as it, in case of files modification inside it with the algorithm **and** a fail the composite traintuple, the retry was done with everything clean and restore except the local folder.
None
None
Launch a compute plan which use the local folder to share hyperparameters between composite traintuples.
None
None

Improve local volume handling in case of retries

---

backend/substrapp/tasks/k8s_backend.py
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/values.yaml

Update kaniko executor and add option to speed up build.
None
None
```
kubectl exec -it -n org-1 backend-org-1-substra-backend-worker-XXX -- mkdir /var/substra/medias/subtuple/test
kubectl cp /PATH/TO/ALGO/algo.tar.gz org-1/backend-org-1-substra-backend-worker-XXX:/var/substra/medias/subtuple/algo.tar.gz
kubectl exec -it -n org-1 backend-org-1-substra-backend-worker-XXX -- tar xzf /var/substra/medias/subtuple/algo.tar.gz -C /var/substra/medias/subtuple/test/
celery -A backend shell --python
from substrapp.tasks.k8s_backend import k8s_build_image
k8s_build_image('/var/substra/medias/subtuple/test/', 'test', True)
```
```
kaniko executor:v1.3.0 --snapshotMode=redo --single-snapshot - 204.925s
kaniko executor:v1.0.0                                       - 701.026s
kaniko executor:v1.0.0 …
```

Update kaniko builder

---

backend/substrapp/tasks/k8s_backend.py

Improve `watch_pod` to handle failed or evicted pod.
Fix #305 
None
None
None
None

Improve watch pod to handle failed or evicted pod

---

backend/requirements.txt
backend/substrapp/ledger/debug_tools.py

This PR adds tools to visualize and dump HLF blocks and transactions.
Usage (from a backend worker pod):
```sh
celery -A backend shell
```
```python
> from substrapp.ledger.debug_tools import *
> end_block = get_ledger_height('mychannel')
> dump_all_transactions(start_block=0, end_block=end_block out_folder='/tmp/blocks')
> txs = get_mvcc_transactions('mychannel', 0, end_block)
> txs[0]
{
'block_number': 43,
'tx_index': 1,
'tx_id': 'fd31631d86e961caf97800d9ff5fae4b12b59ca20c364dc4868408f3c89e6c58'
}
```

ledger: add debug toolbox

---

backend/events/apps.py

The backend receives events from the ledger instructing it to delete compute plan intermediary models.
Historically, the ledger was configured to only have one transaction per block. However, we changed this pradigm a few months back when we changed the ledger configuration to allow multiple transactions per block. **So the block_id is not sufficient anymore to identify a unique transaction**. Since we were using the block_id to uniquely identify celery tasks, when a block containing multiple transactions with events was received, only the first event was processed, and the other ones were skipped. 
As a result, the removal of intermediary models was skipped and many (up to 25% empirically) of intermediary models stayed on disk.
This PR fixes the issue by changing the key to uniquely …

Fix compute plan intermediary models not being deleted

---

backend/requirements.txt

This will invalidate the "pip install" docker cache layer﻿, forcing the system to download the latest version of the rsa library (4.7), fixing a vulnerability in rsa 4.5.

bump kubernetes to 12.0.1

---

backend/substrapp/tests/views/test_views_authentication.py
backend/users/views/user.py

JWT token was no blacklist when logout from substra-backend
None
None
```
curl -L -H "Accept: text/json;version=0.0, */*;version=0.0" -H "Content-Type: application/json" -X POST --data '{"username": "node-1", "password":"p@$swr0d44"}' http://substra-backend.node-1.com/user/login/ -vvv -c cookies
curl -L -H "Accept: text/json;version=0.0, */*;version=0.0" -H "Content-Type: application/json" -X GET http://substra-backend.node-1.com/user/logout/ -vvv -b cookies
curl -L -H "Accept: text/json;version=0.0, */*;version=0.0" -H "Content-Type: application/json" -X POST  http://substra-backend.node-1.com/user/refresh/ -vvv -b cookies 
```
None

Fix JWT token blacklist at logout

---

values/backend-org-1.yaml
values/backend-org-2.yaml

Update peer host values on local with .svc.cluster.local to avoid potential issue with network resolution like "Invalid toplevel subdomain" issue in substra-backend grpc client.
Companion PR : https://github.com/SubstraFoundation/hlf-k8s/pull/128

Update peer host value

---

backend/backend/settings/common.py
docker/substra-backend/Dockerfile

By default, django cache is memory based. With the use of uwsgi process, each worker has its own cache which cause throttle issue (not consistent) depending on which worker responds to the request.
None
None
```
watch -n .01 curl -X POST http://substra-backend.node-1.com/user/login/
```
None

Add shared file based cache in django

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/templates/deployment-celerybeat.yaml
charts/substra-backend/values.yaml

This patch exposes a new configuration option to adapt the period of expired token purge.
It defaults to 24h to match application's behavior when the env var is not set.

[chart] expose FLUSH_REFRESH_EXPIRED_TOKENS_TASK_PERIOD setting

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/configmap-events.yaml
charts/substra-backend/templates/configmap-server-uwsgi.yaml
charts/substra-backend/templates/deployment-server.yaml

The backend-server service port can be different from the port the backend-server container binds to. 
However, we were incorrectly binding to the service port in the backend-server container. 
Since the service definition [targets](https://github.com/SubstraFoundation/substra-backend/blob/master/charts/substra-backend/templates/service-server.yaml#L41) the container port 8000, this would cause connectivity issues whenever the service port would be != 8000.
This PR fixes the uwsgi configuration files so that backend-server always bind to port 8000. There's no need to make this value configurable, as there's no use-case when that would be useful.

fix: binding to service.port instead of 8000

---

backend/backend/settings/deps/ledger.py
backend/backend/urls.py
backend/backend/views.py
backend/substrapp/tests/query/tests_query_compositetraintuple.py
backend/substrapp/tests/views/tests_utils.py
backend/substrapp/tests/views/tests_views_model.py
backend/substrapp/utils.py
backend/substrapp/views/model.py
backend/substrapp/views/utils.py
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/values.yaml
values/backend-org-1.yaml
values/backend-org-2.yaml

Companion PRs:
- https://github.com/SubstraFoundation/substra/pull/261
- https://github.com/SubstraFoundation/substra-tests/pull/182
- https://github.com/SubstraFoundation/substra-chaincode/pull/141
---
Allow end users to export compute task out-models.
The end user can export a model from a node even if the model is owned by a different organization. If the model is not present on the current node, the request is proxied to the relevant node, from which the model is downloaded. This process is transparent to the end user.
```
[Substra CLI/SDK] -> [Node A] -> [model owned by org A]
```
```
[Substra CLI/SDK] -> [Node A] -> [Node B] -> [model owned by org B]
^^ proxy
```
A new configuration option is introduced for each channel: `model_export_enabled`
This permissions is checked on the node …

feat: export models

---

skaffold.yaml

There is an unexpected side effect when using root user with the `dev` skaffold profile.
The volumes are mounted with root ownership but then the user used in compute pod hasn't the permission to write inside shared volumes.

chore: remove root user from dev profile

---

CHANGELOG.md
backend/substrapp/views/model.py

Introduce a new filter param `compute_task_key` that makes it possible to filter models by the compute tasks that produced them.
This change is required because I need to filter models on the key of the compute tasks that produced them. This was introduced in the SDK in https://github.com/Substra/substra/pull/275 and I thought it would work with the filter `compute_task` but it was not the case since this filter only accept a single key and the SDK only sends lists for filters.
Using the Django API tool and using the SDK.
Let me know if I need to introduce a unit test for this, I did not do it since the `compute_task` filter was already untested.

feat: add a new filter key on the model view

---

backend/backend/settings/common.py
docs/settings.md

Following this [comment](https://github.com/Substra/substra-backend/pull/442#issuecomment-1242078535)
This setting seems to not be used anymore, introduced [here](https://github.com/Substra/substra-backend/commit/f6f225b502e940914098f54ece4a51046e66b6f8), removed [here](https://github.com/Substra/substra-backend/commit/4a5a65b3ed7c0c96e2a303ae9ba37a3a562493d9#diff-bbc5395dcf594e6092a31c207b688fe64be94a974d0b4fcc1a4190cfb1494be5)

chore: remove unused setting

---

.github/workflows/labeler.yml

I made a typo when creating the action in #446

ci: fix the labeler action permissions

---

backend/api/errors.py
backend/api/tests/common.py
backend/api/tests/views/conftest.py
backend/api/tests/views/test_utils.py
backend/api/tests/views/test_views_algo.py
backend/api/tests/views/test_views_authentication.py
backend/api/tests/views/test_views_compute_plan_graph.py
backend/api/tests/views/test_views_computeplan.py
backend/api/tests/views/test_views_computetask.py
backend/api/tests/views/test_views_datamanager.py
backend/api/tests/views/test_views_datasample.py
backend/api/tests/views/test_views_info.py
backend/api/tests/views/test_views_metadata.py
backend/api/tests/views/test_views_model.py
backend/api/tests/views/test_views_newsfeed.py
backend/api/tests/views/test_views_performance.py
backend/api/tests/views/test_views_task_profiling.py
backend/api/views/computeplan.py
backend/api/views/computetask.py
backend/api/views/datasample.py
backend/api/views/exception_handler.py
backend/api/views/model.py
backend/api/views/utils.py
backend/organization/tests/views/test_views_organization.py
backend/substrapp/exceptions.py
backend/substrapp/tests/common.py
backend/users/tests/test_user.py

After `substrapp` views being moved to `api` (see https://github.com/Substra/substra-backend/pull/441), some utils, only used by `api`, remain in `substrapp` so this PR move them.
---
- https://app.asana.com/0/0/1202963105406684

chore: split substrapp utils

---

.github/workflows/container-image-backend.yml
.github/workflows/container-image-metrics.yml
.github/workflows/hadolint.yml
.github/workflows/helm.yml
.github/workflows/python.yml

Add a concurrency setting to limit the workflow runs to one per branch.
Reduce the amount of workflows running on our repo. This is similar to what was done in the orchestrator repo (https://github.com/Substra/orchestrator/commit/aef84dd54f8d4267f070358c347c74791a7ce569)

ci: run workflows only on tip of branches

---

backend/api/tests/views/test_views_info.py
backend/backend/views.py
backend/orchestrator/client.py
backend/orchestrator/resources.py

Create a new object `OrchestratorVersion`.
This is the same as the change done in previous PRs to switch the outputs from the orchestrator from a dict to an object.
I tested the change locally by accessing `/info` and everything seems to work.

refactor: orchestrator client return info object

---

backend/substrapp/events/handler_compute_engine.py
backend/substrapp/events/reactor.py
backend/substrapp/events/tests/test_handler_compute_engine.py
backend/substrapp/tasks/__init__.py
backend/substrapp/tasks/tasks_remove_intermediary_models.py

Remove the code that was used to cleanup models in the compute engine.
The `delete_intermediary_models` flag was removed from the API so it will always be `False` in the future, making this code useless.
e2e tests.
Result:
```
============ 110 passed, 7 skipped, 7 warnings in 558.47s (0:09:18) ============
```

feat: stop cleaning up models using delete_intermediary_models

---

CHANGELOG.md
backend/substrapp/compute_tasks/command.py
backend/substrapp/tests/compute_tasks/test_command.py
fixtures/chunantes/metrics/metric0/metrics.py
fixtures/owkin/metrics/metric0/metrics.py

DISCLAIMER: I am not very used to making PRs on the backend, please tell me if anything is missing
https://github.com/Substra/substra-tools/pull/60/files
The `Metrics` class from substratools:
- now inherits from the `GenericAlgo`
- is renamed `MetricAlgo`
- the CLI args are the same as the other algos (inputs, outputs)
e2e tests on the substra tools PR
unit tests

feat: update following the metric change in substratools

---

CHANGELOG.md
backend/substrapp/compute_tasks/command.py
backend/substrapp/compute_tasks/directories.py
backend/substrapp/compute_tasks/execute.py
backend/substrapp/compute_tasks/volumes.py
backend/substrapp/tests/compute_tasks/test_command.py
backend/substrapp/tests/compute_tasks/test_execute.py

Companion PRs:
- https://github.com/Substra/substra-tools/pull/55 (main PR)
- https://github.com/Substra/substra/pull/279
- https://github.com/Substra/substra-backend/pull/473 (this PR)
---
This fixes a bug when the substra-tools command line argument list is too long.

fix: pass substra-tools arguments via a file

---

CHANGELOG.md
backend/api/serializers/performance.py
backend/api/tests/views/test_views_performance.py

Related to [asana task](https://app.asana.com/0/1200346939311555/1202721024997169)
Before Generic task, on frontend side performance series were build based on `metric key`. Now the equivalent unique key to identify a perf is `(task_key, algo_key, output_identifier)`. The output identifier should now be returned by compute plan perf endpoint.
This PR adds the output_identifier to metric field.
New api response : 
```javascript
{
"compute_task": {
"key": "d4fea647-f799-436e-9181-3af75a861cec",
"data_manager_key": "e7ccd2d4-b48d-4c3b-aa64-4cfbb42051d4",
"algo_key": "8984a47c-7c34-4d54-8936-f9839c64acdb",
"rank": 2,
"round_idx": null,
"data_samples": [
"f7beeee6-ce51-4f67-99cd-fa5237b73c86"
],
"worker": "MyOrg1MSP"
},
"metric": {
"key": "8984a47c-7c34-4d54-8936-f9839c64acdb",
"name": …
```

feat: add output identifier in compute plan perf api

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/ingress.yaml

The `server.ingress.ingressClassName` value was not used properly by the Chart.
Now if you set the ingress class name in your Values your ingress will have the right class.
N/A

fix: set ingressClassName correctly on the Ingress resource

---

backend/api/management/commands/generate_fixtures.py
backend/api/tests/asset_factory.py
backend/api/tests/views/test_views_algo.py
backend/api/tests/views/test_views_computetask.py
backend/api/tests/views/test_views_model.py
backend/api/tests/views/test_views_performance.py

Provides inputs/outputs to the algo and compute task factory, instead of inferring static values from category.
- It removes dependency to the categories we want to deprecate.
- It provides valid task input keys instead of random uuid which is needed to test serializers (required for #458).
Before
```python
algo = create_algo(
category=Algo.Category.ALGO_SIMPLE,
)
train_task = create_computetask(
compute_plan,
algo,
category=ComputeTask.Category.TASK_TRAIN,
...
)
metric = create_algo(
category=Algo.Category.ALGO_METRIC,
)
test_task = create_computetask(
compute_plan,
metric,
category=ComputeTask.Category.TASK_TEST,
...
)
```
After:
```python
algo = create_algo(
inputs=factory.build_algo_inputs(["datasamples", "opener"]),
outputs=factory.build_algo_outputs(["model"]),
)
train_task = …
```

test: provide algo inputs outputs to factory

---

CHANGELOG.md
backend/api/tests/views/test_views_compute_plan_graph.py
backend/api/views/compute_plan_graph.py

[Asana card](https://app.asana.com/0/1200346939311555/1203023779458048/f)
This simple PR adds the `kind` for each task's input and output.
This is needed for the frontend to be able to compute a proper graph layout, without relying on the task categories.
Note: Internally the input and output are still made up based on the categories and an hardcoded logic. This will be changed in a later PR.
⚠️ This is an API BREAKING CHANGE (See changes below)
frontend and substra needs to be updated. Here are the companion PRs:
- [frontend](https://github.com/Substra/substra-frontend/pull/114)
- ~~substra~~: Not impacted
Response before:
```
{
"key": "c1d5dc97-327a-4063-a3a3-a5388cfedee1",
"rank": 3,
"worker": "MyOrg1MSP",
"status": "STATUS_DONE",
"category": "TASK_PREDICT",
"inputs": [ …
```

feat(workflow_graph): Added the input and output kinds in response

---

backend/api/management/commands/generate_fixtures.py

Fix the generate fixures command which break the CI following this [PR](https://github.com/Substra/substra-backend/pull/487).

fix: generate fixtures command after removing algo category

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/values.yaml
examples/values/backend-org-1.yaml
examples/values/backend-org-2.yaml

Previously, the Redis data of the compute engine was not stored in a Persistent Volume. Hence, in the event of a Redis outage, tasks could disappear without ever being processed by the workers. **This PR updates the Helm chart so that Redis data are written on a Persistent Volume.**
Moreover, by default, Redis uses snapshot-based persistence (RDB). The compute engine use case requires better durability guarantees (and not necessarily a high throughput). **This PR updates the Redis config, so that [append-only file based persistence is used](https://redis.io/docs/manual/persistence/)**.
_Note: In the development environment, the data is not persisted in a persistent volume, similar to what is done with PostgreSQL data._
- in a local dev environment, by checking that Persistent Volume and …

chore: enable redis persistence

---

CHANGELOG.md
backend/api/migrations/0028_data_migration_compute_task_output.py

Signed-off-by: Kelvin Moutet <kelvin.moutet@owkin.com>
When we do an update of substra-backend with data populated before api migrations 028 we face this issue 
```python
Operations to perform:
Apply all migrations: auth, authtoken, contenttypes, django_celery_results, localrep, organization, sessions, sites, substrapp, token_blacklist, users
Running migrations:
Traceback (most recent call last):
File "/usr/src/app/manage.py", line 15, in <module>
execute_from_command_line(sys.argv)
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
utility.execute()
File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File …
```

fix: api migration 028

---

CHANGELOG.md
backend/backend/settings/common.py
docs/settings.md
examples/values/backend-org-1.yaml
examples/values/backend-org-2.yaml

The default value was not compatible with a locally deployed frontend.
See https://github.com/adamchainz/django-cors-headers#csrf-integration
This change is quite minimal: the setting is created from env var.
Locally, with this change I'm able to login through the frontend.

fix: Allow to set CSRF_TRUSTED_ORIGINS

---

CHANGELOG.md
README.md

Remove RabbitMQ patch references in changelog.
None.

docs: Remove RabbitMQ patch for Apple Silicon chips

---

CHANGELOG.md
backend/api/serializers/computetask.py

Fix storage address for compute task inputs/output.
The value is expected to be overwritten by the child serializer, (see [here](https://github.com/Substra/substra-backend/blob/main/backend/api/serializers/model.py#L40) for instance).
As child serializer is not directly set as an attribute to the parent serializer, the context is not automatically provided under the hood by DRF and we need to set it manually.
Manual check via the DRF UI.

fix: compute task outputs/inputs valid storage address

---

CHANGELOG.md
backend/api/serializers/__init__.py
backend/api/serializers/computetask.py
backend/api/tests/views/test_views_computetask.py
backend/api/views/computetask.py

New endpoints to list input/output assets.
The deprecated fields will be removed in #509, after the frontend is switched to the new endpoints.
```
GET /task/873ec870-54a6-46ad-a5f9-d3a509b1a22e/input_assets/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"count": 2,
"next": null,
"previous": null,
"results": [
{
"identifier": "datasamples",
"asset": {
"creation_date": "2022-10-03T08:25:13.806075Z",
"data_manager_keys": [
"c5120265-7a8d-4eb8-83c1-3e200c4c0bba"
],
"key": "9db9231a-9b54-4e12-bcbf-c3802868d00f",
"owner": "MyOrg1MSP",
"test_only": false
}
},
{
"identifier": "opener",
"asset": {
"creation_date": "2022-10-03T08:25:13.797115Z",
"description": {
"storage_address": …
```

feat: new endpoints to list input/output assets

---

UPGRADE.md

Signed-off-by: Kelvin Moutet <kelvin.moutet@owkin.com>
Fix upgrade doc as the change happened between 0.29.0 and 0.30.0 and not between 0.28.0 and 0.29.0
See first commit of this diff https://github.com/Substra/substra-backend/compare/0.29.0...0.30.0

fix: upgrade substra-backend versions for app renaming

---

CHANGELOG.md
backend/substrapp/compute_tasks/command.py
backend/substrapp/compute_tasks/context.py
backend/substrapp/compute_tasks/volumes.py
backend/substrapp/tasks/tasks_compute_task.py
backend/substrapp/tests/compute_tasks/conftest.py
backend/substrapp/tests/compute_tasks/test_asset_buffer.py
backend/substrapp/tests/compute_tasks/test_command.py
backend/substrapp/tests/tasks/test_compute_task.py

Do not use task category in the compute engine
Local E2E and CI

refactor: remove task category from compute engine

---

CHANGELOG.md
backend/api/tests/views/test_views_computetask.py
backend/api/views/computetask.py

Signed-off-by: Jérémy Morel <jeremy.morel@owkin.com>
Adds filtering on the asset_kind property to `/task/<key>/input_assets/` and `/task/<key>/output_assets/`.
It supports multi values with CSV: `/task/<key>/input_assets/?kind=ASSET_DATA_SAMPLE,ASSET_MODEL`.
Through DRF UI and unit tests.

feat: filter task in/outputs by kind

---

.github/workflows/migration.yml

The second pip update is not necessary since it's done 2 steps before.

ci: only update pip once

---

CHANGELOG.md
backend/users/tests/test_user.py
backend/users/views/user.py

Signed-off-by: Jérémy Morel <jeremy.morel@owkin.com>
- Adds validation for username so that the actual creation doesn't fail with an IntegrityError
- Adds validation on empty password before using the configured validators. This is necessary because the zxcvbn validator will raise a list index out of range exception on an empty password string. See https://github.com/dwolfhub/zxcvbn-python/issues/64
- Decodes the url encoded `kwargs.get('username')` so that the username is properly handled (`John Doe` is a valid username).
Manually.

feat: improved user creation validation

---

CHANGELOG.md
backend/api/tests/views/test_views_datamanager.py
backend/api/views/datamanager.py

Without this fix, SDK calls to `client.list_dataset()` returns results missing the `train_data_sample_keys` and `test_data_sample_keys` field. This in turn is interpreted by the SDK as there being no data samples associated with the data manager.
```py
>>> client.list_dataset()
[{
"key": "f741a383-e9ae-4ceb-9ff5-0803bec98589",
"name": "XXX",
"owner": "MyOrg2MSP",
"permissions": {
"process": {
"public": false,
"authorized_ids": [
"MyOrg2MSP",
"MyOrg1MSP"
]
}
},
"type": "npy",
"train_data_sample_keys": [],             # <- even though there are data samples
"test_data_sample_keys": [],              # <- even though there are data samples
[...]
}]
```
If accepted, this fix should be backported to release 0.31.x.

feat: return {train,test}_data_sample_keys fields in data manager "list" API responses

---

CHANGELOG.md
backend/orchestrator/computetask_pb2.py
backend/orchestrator/computetask_pb2.pyi
backend/substrapp/compute_tasks/lock.py

Finish removing task specific date (`train`, `test`, `predict`,  `aggregate` and `composite`)
- https://github.com/Substra/orchestrator/pull/46
CI E2E

feat: remove task specific data

---

CHANGELOG.md
backend/users/views/authentication.py

Access token in Substra is secured by separating the cookie in 2 cookies: header_payload and signature. The header_payload cookie has a 24h expiration date but the signature had none. Because of this once the header_payload expired there was a bug as the signature was still existing which blocked the creation of a new pair of cookies (be it from the refresh token or entering credentials again), which led to the user having to delete the signature cookie manually to resolve the issue.
This fix only give the same expiration date to the signature cookie so that it disappears at the same time as header_payload. If the user still has a refresh token (1 week expiration date), a new header_payload-signature pair will be fetched automatically, otherwise credentials have to be entered anew.

fix: Add same expiration date that header_payload to signature cookie

---

CHANGELOG.md
examples/secrets/skaffold.yaml
skaffold.yaml

Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
This move the secrets creation in another module so it can be run before deploying on Helm.

fix(skaffold): create secrets before deploying releases

---

CHANGELOG.md
examples/secrets/skaffold.yaml
examples/values/serviceAccounts/skaffold.yaml
skaffold.yaml

- https://github.com/Substra/hlf-k8s/pull/147
- https://github.com/Substra/orchestrator/pull/144
Update skaffold schema to `v4beta2` due to migration to Skaffold version `2.x.x` which was compatible with our schemas.
Update skaffold schema to `v4beta2` due to migration to Skaffold version `2.x.x` which was compatible with our schemas and leverages new `setValueTemplate` instead of `artifactOverrides`.
Local tests & CI

fix(skaffold): Skaffold spawns too many backends

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Add templates for issues on GitHub. 
Include a bug report form, a link to the documentation for documentation improvements, a link to Substra Slack for questions, and the option to open a blank (non templated) issue for all other needs.

chore: add issues templates

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/deployment-api-events.yaml
charts/substra-backend/templates/deployment-scheduler-worker.yaml
charts/substra-backend/templates/deployment-scheduler.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker-events.yaml
charts/substra-backend/templates/job-migrations.yaml
charts/substra-backend/templates/statefulset-worker.yaml
charts/substra-backend/values.yaml

This adds a new helm "function" that defaults the image tag to the AppVersion if it is not provided.
The removes one spot where the app version needed to be copied at releases.
This is already in place on the frontend, I'd been meaning to port this to the other repos -- also see https://github.com/Substra/orchestrator/pull/159 which is this but for the orchestrator.
Check it works the same way:
```
git switch main
helm template charts/substra-backend > old-render.yaml
git switch chore-helm/default-appversion
helm template charts/substra-backend > new-render.yaml
diff old-render.yaml new-render.yaml
```
I also tried `helm template charts/substra-backend --set server.image.tag=woop` to check it (and only it) was set the given value.

chore(helm): default image tag to AppVersion

---

CHANGELOG.md
backend/api/serializers/task_profiling.py
backend/api/tests/views/test_views_task_profiling.py

Change durations format to microseconds for task duration & execution rundown steps in task profiling.
Companion PR : https://github.com/Substra/substra-frontend/pull/165

feat: Change tasks & steps duration format in task profiling to microseconds

---

CHANGELOG.md
backend/api/tests/views/test_views_performance.py
backend/api/views/performance.py

Signed-off-by: Milouu <milan.roustan@owkin.com>
Add new filters for filtering performances export by metric_key and metric_output_identifier. This is needed in the frontend to be able to download only the performances of a single performance chart.
Companion PR: https://github.com/Substra/substra-frontend/pull/156

chore: Add new filters for performances export

---

README.md

Sorry for the very small PR, I saw the notice at the bottom the the readme and wondered "Why is that part of the License ?" and then realized the title had the wrong level, so just fixing this.
- Fix the level of title of `Running the backend on arm64 architecture`
- Ensure the License stays at the bottom, to be visible
- Missing comma
- fix `<ul>` RST syntax
https://github.com/ewjoachim/substra-backend/blob/patch-1/README.md
Readme screenshot:
I hereby certify that I agree with the terms of the DCO, but signing-off my commit means I'd need to fork the repo and amend. If that's ok with you, I think a change of this scope might not be worth the effort :)

docs: Small improvement of readme

---

CHANGELOG.md
backend/api/serializers/performance.py
backend/api/tests/views/conftest.py
backend/api/tests/views/test_views_computetask.py
backend/api/tests/views/test_views_performance.py
backend/api/views/performance.py

- https://github.com/Substra/substra-frontend/pull/180
Try to improve loading in performance page. Two strategies have been put in place:
1. Using prefetch for FunctionOutput and using it in the serializer (instead of making a request for each function on FunctionOutput)
2. Removing `data_samples` from the request, as it doesn't seem to be used in the frontend.
The point 2 is more controversial, as it breaks the current architecture of returning linked data on eac hrequest. However, it implies reaching a n+ 3 level (as the data_samples are ordered on `api_taskdatasample.order`, which is maybe not needed .

fix: improve perf loading

---

CHANGELOG.md
backend/substrapp/compute_tasks/command.py

Refactor 3 loops on inputs in `substrapp` in only one
CI

chore: refactor input loop in `get_exec_command_args`

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/configmap-oidc.yaml
examples/values/backend-org-1.yaml

This fixes an issue with #609 which broke the CI, basically
e2e tests

fix: avoid nil env vars in chart

---

backend/dev-requirements.txt
pyproject.toml

Closes https://github.com/Substra/substra-backend/pull/629
Add a new warning filter because of https://github.com/pytest-dev/pytest-xdist/issues/825#issuecomment-1292341220

chore: bump pytest-xdist to 3.2.1

---

CHANGELOG.md
backend/substrapp/compute_tasks/image_builder.py
backend/substrapp/kubernetes_utils.py

This PR does two things to patch instable behaviours in Kaniko observed lately. 
- Increase the number of attempts, hence the time we wait, in the [watch_pod](https://github.com/Substra/substra-backend/blob/e813ab5a71bb2051b508dcd741d1dce436305b8a/backend/substrapp/kubernetes_utils.py#L81) function.
- Catch exception raised by the [get_pod_logs](https://github.com/Substra/substra-backend/blob/e813ab5a71bb2051b508dcd741d1dce436305b8a/backend/substrapp/kubernetes_utils.py#L235), so that it does not crash the worker BEFORE deleting the kaniko pod it created. 
Not yet, card created to add unit test as follow-up.

fix: increase max attempts for kaniko and return logs instead of raising

---

CHANGELOG.md
backend/api/tests/views/test_views_compute_plan_graph.py
backend/api/views/compute_plan_graph.py
backend/api/views/computetask.py

-  Adds function name to workflow view so that the frontend can display the function name for each task.
-  Allows ordering by function name in compute tasks list now that the frontend allow it. 
Companion PR : https://github.com/Substra/substra-frontend/pull/188

feat: Add functionName to workflow view & allow ordering in tasks

---

CHANGELOG.md
backend/substrapp/compute_tasks/errors.py
backend/substrapp/compute_tasks/image_builder.py
backend/substrapp/tests/compute_tasks/test_image_builder.py
backend/substrapp/tests/test_kubernetes_utils.py

Workaround for [this Celery bug](https://github.com/celery/celery/issues/6990)

fix: make BuildError serialisable by Celery in case of retry

---

CHANGELOG.md
metrics-exporter/requirements.txt
skaffold.yaml

Add `redis` in metrics_exporter dependencies to fix `server.metrics`

fix: metrics exporter redis not found

---

CHANGELOG.md
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml

- Performance is now unique regarding a ComputeTaskOutput and a Metric ([#634](https://github.com/Substra/substra-backend/pull/634))
- BREAKING: `TaskProfiling` do not use `create_or_update` but retry with `PUT` if error is `409` ([#636](https://github.com/Substra/substra-backend/pull/636))
- Raise a serializable Exception so that CeleryRetryError won't crash ([#641](https://github.com/Substra/substra-backend/pull/641))
- Do not retry on non-timeout build errors ([#641](https://github.com/Substra/substra-backend/pull/641))
- Metric from Performance ([#650](https://github.com/Substra/substra-backend/pull/650))

chore: release 0.37.0

---

backend/backend/views.py
backend/users/models/token.py

If an user who hasn't done so before makes multiple requests to `/api-token-auth` at the same time, the backend runs into concurrency issues and might error out due to database integrity violations.
This makes the whole operation atomic.
⬇️

fix: concurrent issuance of implicit bearer tokens

---

CHANGELOG.md
backend/api/events/sync.py
backend/api/serializers/__init__.py
backend/api/serializers/computetask.py
backend/api/tests/views/test_views_computetask.py
backend/api/tests/views/test_views_performance.py
backend/api/views/computetask.py

- https://github.com/Substra/substra-tests/pull/256
- https://github.com/Substra/substra/pull/361
- https://github.com/Substra/substrafl/pull/129
:warning: **DO NOT MERGE** until the frontend is switched to the new endpoints.
Following #496, removing deprecated field.
- input: addressable, permissions
- output: values
Fixes FL-568
---
- https://app.asana.com/0/0/1203097915891016

feat: remove deprecated input output values

---

CHANGELOG.md
docs/localdev.md

- https://github.com/Substra/substra/pull/362
Remove references to `substra` commands in documentation
Fixes FL-489

chore: remove references to `substra` commands (namely `substra login`)

---

examples/values/backend-org-1.yaml
examples/values/backend-org-2.yaml

In #658, I removed alternative DB credentials from the server app.
This PR forces the DB settings to be the same in Skaffold as in localdev.
The main point of this is to make development a bit easier by always using the same credentials in all situations. Basically if you're developing on your machine the connection string will always be `postgresql://backend:backend@${HOST}/backend_default`, and `./manage.py shell` won't fail because you're on the profile with the wrong DB creds.
There are a lot of different development set-ups for Substra, so I think it's good to avoid having too much variance.
I'd agree the names (`backend:backend` and `backend_default`) aren't necessarily the best, but honestly I just want them to be the same everywhere.
- [-] ~~[changelog](../CHANGELOG.md) was …

chore: single dev DB creds

---

CHANGELOG.md
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml

- New `SECRET_KEY_PATH` and `SECRET_KEY_LOAD_AND_STORE` environment variables ([#668](https://github.com/Substra/substra-backend/pull/668))

chore: release 0.39.0

---

.github/workflows/docker-build.yaml

Pass arguments from the `substra-gha-workflows` to `substra-backend` allowing publishing docker image from any commit.

feat: add force publish from substra-gha-workflows

---

CHANGELOG.md
backend/api/tests/views/test_views_performance.py
backend/api/views/performance.py

- https://github.com/Substra/substra/pull/372
- https://github.com/Substra/substra-frontend/pull/222
Remove pagination in performance endpoints, as we always need all of them. 
Note: alternative implementation would be to iterate on all pages in `<task_id>/perf/` in all case,  in the frontend and in the SDK.
Fixes FL-1092

fix: remove pagination on `<task_id>/perf`

---

charts/substra-backend/CHANGELOG.md

Fix the helm changelog featuring an "Unreleased" section (right now helm charts are released directly upon reaching `main`)

fix(helm): 22.6.0 changelog

---

backend/api/events/sync.py
backend/api/models/computeplan.py
backend/api/tests/views/test_views_computeplan.py
backend/backend/settings/common.py
backend/users/views/user.py

one line PR to add an exclude as a fix to "external" users being considered as a UserAwaitingApproval
basically like "deleted" those username are the only kind of users allowed to not have a channel without beeing a UserAwaitingApproval
Fixes FL-989

fix: exclude "external" from UserAwaitingApproval

---

CHANGELOG.md
backend/api/views/compute_plan_graph.py

Increase the number of tasks displayable in the frontend workflow from 1000 to 5000.

chore: Increase workflow maxsize for frontend

---

CHANGELOG.md
backend/api/serializers/task_profiling.py
backend/api/tests/asset_factory.py
backend/api/tests/views/conftest.py
backend/api/tests/views/test_views_task_profiling.py
backend/api/views/task_profiling.py
backend/substrapp/tasks/tasks_compute_task.py
backend/substrapp/tests/tasks/test_compute_task.py
backend/substrapp/utils/url.py

(4 first commits are refactoring to `pytest`)
Fixes FL-496

feat: allow retries on task profiling steps

---

CHANGELOG.md
backend/api/errors.py
backend/api/tests/views/test_exception_handler.py
backend/api/tests/views/test_views_datamanager.py
backend/api/tests/views/test_views_datasample.py
backend/api/tests/views/test_views_function.py
backend/api/views/compute_plan_graph.py
backend/api/views/datasample.py
backend/api/views/exception_handler.py
backend/api/views/utils.py
backend/backend/views.py
backend/users/tests/test_user.py
backend/users/views/authentication.py
backend/users/views/user.py

On error (HTTP 4XX or 5XX), our API's JSON reponses are inconsistent. This is in large part because our own code returns `{"message": ...}` but DRF returns `{"detail": ...}`.
This changes all instances were we use `message` to `detail` instead (including in non-error responses).
Companion PR: https://github.com/Substra/substra/pull/379
This PR replaces https://github.com/Substra/substra-backend/pull/699, a previous attempt at this
I'm not sure how to test this works correctly :)

chore!: rename the "message" field in API responses to "detail"

---

examples/values/backend-org-1.yaml
examples/values/backend-org-2.yaml

This removes this warning:
```
W0814 16:50:43.195377   70146 warnings.go:70] annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead
```
`skaffold run`

chore: replace deprecated kubernetes.io/ingress.class

---

CHANGELOG.md
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml

- New `SECRET_KEY` optional environment variable ([#671](https://github.com/Substra/substra-backend/pull/671))
- `/api-token-auth/` and the associated tokens can now be disabled through the `EXPIRY_TOKEN_ENABLED` environment variable and `server.allowImplicitLogin` chart value ([#698](https://github.com/Substra/substra-backend/pull/698))
- Tokens issued by `/api-token-auth/` can now be deleted like other API tokens, through a `DELETE` request on the `/active-api-tokens` endpoint ([#698](https://github.com/Substra/substra-backend/pull/698))
- Increase the number of tasks displayable in frontend workflow [#697](https://github.com/Substra/substra-backend/pull/697)
- BREAKING: Change the format of many API responses from `{"message":...}` to `{"detail":...}` …

chore: release 0.41.0

---

CHANGELOG.md
charts/substra-backend/values.yaml
examples/values/backend-org-1.yaml
examples/values/backend-org-2.yaml
examples/values/backend-org-3.yaml

- https://github.com/Substra/substra-tools/pull/86 (main)
- https://github.com/Substra/substra-tests/pull/284
- https://github.com/owkin/substra-ci/pull/129
- https://github.com/Substra/substra-backend/pull/736
- https://github.com/Substra/substra/pull/389

chore: remove minimal and workflow substra-tools images

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/templates/statefulset-builder.yaml

Use the SA ` xxx-builder`  instead of ` xxx-worker`  in `builder`

fix: builder using builder SA

---

backend/substrapp/events/reactor.py

[sub]fix: adapt to pydantic 2.x.x 

---

.github/workflows/helm.yml
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml

[sub]chore: upgrade chart

---

.github/workflows/docker-build.yaml

The input was defined for manual runs but not passed to the `docker-build` from `substra/substra-gha-workflows`, it had no effect

chore(ci): pass force-publish input to docker-build workflows

---

.github/workflows/helm.yml
charts/substra-backend/Chart.yaml

ArtifactHub currently recommends checking out the alphas from this branch instead of our stable version.
They want a proprietary field being set: https://artifacthub.io/docs/topics/annotations/helm/

chore: add chart prerelease annotation for ArtifactHub 

---

backend/requirements.txt

issue with pip when installing 2.9.3

chore: bump psycopg2-binary from 2.9.3 to 2.9.9

---

CHANGELOG.md
backend/api/views/datasample.py
backend/image_transfer/decoder.py
backend/image_transfer/encoder.py
backend/substrapp/serializers/utils.py
backend/substrapp/utils/__init__.py
backend/substrapp/utils/safezip.py
backend/substrapp/utils/tarsafe.py

Fixes FL-1470
It will also unlock this dependency update (which nicely flagged it: https://github.com/Substra/substra-backend/pull/813)

fix: enforce use of `safezip` and `tarsafe`

---

CHANGELOG.md
backend/api/tests/views/test_views_function.py
backend/api/views/function.py
backend/backend/settings/server/common.py
backend/backend/settings/server/dev.py
backend/backend/settings/server/prod.py
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/configmap-settings.yaml

fix: check builder exists on create

---

CHANGELOG.md
README.md
backend/dev-requirements.txt
changes/861.changed
pyproject.toml

chore: set up towncrier for changelog management

---

.github/workflows/python.yml
backend/requirements.txt

Run CI in 3.11 since our Docker image is based of 3.11

chore: run CI in 3.11

---

changes/878.changed
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/values.yaml

chore: switch default S3 storage to MinIO

---

.github/workflows/helm.yml

Companion:
- https://github.com/Substra/substra-backend/pull/881
- https://github.com/Substra/orchestrator/pull/405
- https://github.com/Substra/substra-frontend/pull/333
Example of working worklfow (with fake publish):
- https://github.com/Substra/substra-backend/actions/runs/8628929572

chore: allow alpha chart publication

---

backend/api/serializers/task_profiling.py
backend/substrapp/tasks/tasks_compute_task.py
backend/substrapp/tests/tasks/test_compute_task.py
changes/1517.removed

Remove the task profiling step `build_image`. The function will get its own profiling with different steps in another contribution.
Fixes FL-1517
- https://github.com/Substra/substra-frontend/pull/332

chore: remove building from task profiling

---

changes/866.changed
docker/substra-backend/Dockerfile

closes FL-1530
12 middle and 8 low

chore: change to ubuntu base image for docker image

---

backend/backend/settings/common.py
backend/builder/image_builder/image_builder.py
backend/substrapp/compute_tasks/compute_pod.py
backend/substrapp/kubernetes_utils.py
backend/substrapp/tasks/task.py
changes/892.added
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/templates/deployment-api-events.yaml
charts/substra-backend/templates/deployment-registry-prepopulate.yaml
charts/substra-backend/templates/deployment-worker-events.yaml
charts/substra-backend/templates/statefulset-builder.yaml
charts/substra-backend/templates/statefulset-worker.yaml
charts/substra-backend/values.yaml
docs/settings.md

chore: add limits and requests configuration in values (#867)

---

examples/secrets/secret-harbor-dockerconfig.yaml
examples/secrets/secret-harbor-tls.yaml
examples/secrets/skaffold.yaml
examples/values/coredns-custom-harbor.yaml
examples/values/harbor.yaml
skaffold.yaml

feat: add Harbor as a skaffold profile

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-registry-prepopulate.yaml

fix: missing resources field in initContainers

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/job-migrations.yaml

Closes FL-1560
```bash
k logs backend-org-1-substra-backend-migrations-4krgq -n org-1
user created org-1
user created org-1-yourchannel
organization successfully created
organization_id=First Organization
organization successfully created
organization_id=MyOrg2MSP
organization successfully created
organization_id=MyOrg3MSP
outgoing organization successfully created
organization_id=First Organization
outgoing organization successfully created
organization_id=MyOrg2MSP
outgoing organization successfully created
organization_id=MyOrg3MSP
```
On the orchestrator db:
```sql
orchestrator=# select * from organizations;
id         |   channel   |         creation_date         |                        address                         
--------------------+-------------+------------------------------ …
```

chore(charts/substra-backend): handle whitespaced orgnames

---

backend/api/events/sync.py
backend/api/tests/test_sync.py
changes/924.fixed

Bypass `AssetFailureReport` creation whenerror type is `ERROR_TYPE_INTERNAL`. It fixes errors when the backend receives an internal error from the orchestrator (without log address/checksum, as they are not provided in this scenario)
Fixes FL-1583

fix: bypass asset failure creation when internal error

---

backend/substrapp/kubernetes_utils.py
charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.lock
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/deployment-api-events.yaml
charts/substra-backend/templates/deployment-registry-prepopulate.yaml
charts/substra-backend/templates/deployment-scheduler-worker.yaml
charts/substra-backend/templates/deployment-scheduler.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker-events.yaml
charts/substra-backend/templates/job-migrations.yaml
charts/substra-backend/templates/statefulset-builder.yaml
charts/substra-backend/templates/statefulset-worker.yaml
charts/substra-backend/values.yaml

Fixes FL-1453
This PR introduces the following changes to the security context: 
- for all containers and initContainers: 
- `spec.containers[*].securityContext.allowPrivilegeEscalation=false`
- `spec.containers[*].securityContext.runAsNonRoot=true`
- `spec.containers[*].securityContext.seccompProfile.type=RuntimeDefault`
- `spec.containers[*].securityContext.capabilities.drop=["ALL"]`
The exceptions are : `add-cert` initContainer in several pods (if the local CA feature is used), `wait-registry` initContainer and `kaniko` initContainer in the registry-prepopulate pod. 
- for all pods: 
- `spec.securityContext.runAsNonRoot=true`
- `spec.securityContext.seccompProfile.type= RuntimeDefault`
The exceptions are the kaniko pods spawned by the builder.
Deploy locally (with skaffold), and then …

chore: enforce pod security standards

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/job-migrations.yaml
charts/substra-backend/templates/secret-add-account.yaml
charts/substra-backend/values.yaml

feat(charts): allow using existing secrets for addAccountOperator

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/deployment-api-events.yaml
charts/substra-backend/templates/deployment-scheduler-worker.yaml
charts/substra-backend/templates/deployment-scheduler.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker-events.yaml
charts/substra-backend/templates/secret-redis.yaml
charts/substra-backend/templates/statefulset-builder.yaml
charts/substra-backend/templates/statefulset-worker.yaml
charts/substra-backend/values.yaml

feat(charts): allow using existing secret for redis

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/statefulset-builder.yaml

fix(charts): restart pods after cm updates

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/values.yaml

Closes FL-1663
```bash
curl http://localhost:4566/_localstack/health
{"services": {"acm": "available", "apigateway": "available", "cloudformation": "available", "cloudwatch": "available", "config": "available", "dynamodb": "available", "dynamodbstreams": "available", "ec2": "available", "es": "available", "events": "available", "firehose": "available", "iam": "available", "kinesis": "available", "kms": "available", "lambda": "available", "logs": "available", "opensearch": "available", "redshift": "available", "resource-groups": "available", "resourcegroupstaggingapi": "available", "route53": "available", "route53resolver": "available", "s3": "available", "s3control": "available", "scheduler": "available", "secretsmanager": "available", "ses": "available", "sns": "available", "sqs": …
```

chore(charts): disable localstack services

---

backend/image_transfer/encoder.py
backend/requirements.txt
changes/990.removed

chore: remove tqdm

---

backend/api/events/sync.py
backend/api/models/computeplan.py
backend/api/tests/models/test_models_computeplan.py
backend/api/views/computetask.py
changes/998.changed

feat: cp duration starts with build

---

backend/builder/kubernetes.py
backend/builder/tests/test_image_builder.py
backend/builder/tests/test_kubernetes.py

fix: pending error not repackaged

---

backend/backend/settings/api/events/common.py
backend/backend/settings/common.py
backend/backend/settings/deps/celery.py
backend/backend/settings/dev.py
backend/backend/settings/prod.py
backend/backend/settings/worker/events/common.py
backend/requirements.txt
changes/995.changed

feat: remove `django-celery-results` and replace by redis

---

backend/api/models/computeplan.py
backend/api/models/function.py
backend/builder/exceptions.py
backend/builder/image_builder/image_builder.py
backend/builder/tasks/task.py
backend/builder/tasks/tasks_build_image.py
backend/builder/tests/test_image_builder.py
backend/builder/tests/test_task_build_image.py
changes/997.added

Fixes FL-1659
- https://github.com/Substra/substra-tests/pull/383

feat: check computeplans before running function

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/deployment-api-events.yaml
charts/substra-backend/templates/deployment-scheduler-worker.yaml
charts/substra-backend/templates/deployment-scheduler.yaml
charts/substra-backend/templates/deployment-server.yaml
charts/substra-backend/templates/deployment-worker-events.yaml
charts/substra-backend/templates/statefulset-builder.yaml

feat: wait redis on start

---

charts/substra-backend/CHANGELOG.md
charts/substra-backend/Chart.yaml
charts/substra-backend/README.md
charts/substra-backend/templates/_helpers.tpl
charts/substra-backend/templates/deployment-registry-prepopulate.yaml
charts/substra-backend/values.yaml

feat: make init dependencies image customizable

---

docker/ca-cert-injector/Dockerfile
docker/substra-backend/Dockerfile

Fix error in substra-ci due to a removal of ubuntu mantis repository.
Ci ran well with the update (test only on sdk): https://github.com/owkin/substra-ci/actions/runs/12429276467

chore: switch from mantis (`23.10`) to next LTS (`24.04`)
