docker/start.py
After the repo renaming, there is an error on the flake 8 test on a file.
This PR fix this error !
=> Fix flake 8 line too long.

.github/CODEOWNERS
This PR updates the list of codeowners as discussed some time ago with the new organisation.
=> update codeowner according to orga

.flake8
Following https://github.com/SubstraFoundation/substra-backend/pull/27
=> Add medias to flake8

backend/node-register/apps.py, docker/start.py
=> Fix proposal for backend start up (issue #23)

backend/substrapp/tasks/tasks.py
Make it clearer which type of tuple functions take
=> tasks: Update test/train tuple functions parameter names

backend/substrapp/tasks/tasks.py
To find the tuple type associated with the input models of a "training" tuple (aggregatetuple, traintuple and composite_traintuple) the smart contract `queryModelDetails` is used.
A bit of reworking also: 
- internal global var for tuple type (to avoid typo)
- when preparing materials, merge get/put methods to a single prepare methods (it's then simpler to manage the different cases for preparing models)
=> Handle tasks execution for aggregate tuple

backend/substrapp/tests/assets.py, backend/substrapp/views/filters_utils.py
* allow filtering of aggregatuple (same as composite_traintuple)
* fix filtering of all algos
* fix filtering of models (now supports aggregatetuple)
=> filter aggregate models

backend/substrapp/tasks/tasks.py, backend/substrapp/tests/tests_tasks.py
The tests for the `get_model` and `put_model` have been removed.
=> fix tests for aggregate

charts/substra-backend/templates/configmap-server.yaml, charts/substra-backend/templates/deployment-scheduler.yaml, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/templates/deployment-worker.yaml, charts/substra-backend/values.yaml
See main PR: https://github.com/SubstraFoundation/hlf-k8s/pull/16
=> Refactor CA Cert secret names

backend/substrapp/serializers/ledger/computeplan/serializer.py, backend/substrapp/tests/views/tests_views_computeplan.py
Companion PRs:
* [substra](https://github.com/SubstraFoundation/substra/pull/45)
* [substra-chaincode](https://github.com/SubstraFoundation/substra-chaincode/pull/41)
* [substra-tests](https://github.com/SubstraFoundation/substra-tests/pull/21)
=> Generic compute plan

backend/substrapp/tasks/tasks.py
Local volume was created only for tuple of rank 0.
This is causing a bug as the tuple of rank 0 may be executed on a different worker than the worker for the tuple of rank 1.
Regression introduced by commit b640a5518ff0e5381b10dd4aad40a0a1489abed5
Can be tested with substra-tests:
```
pytest tests/test_execution_compute_plan.py::test_compute_plan_aggregate_composite_traintuples
```
=> Fix local volume for tuples

charts/substra-backend/Chart.yaml, charts/substra-backend/templates/configmap-server.yaml, charts/substra-backend/templates/deployment-scheduler.yaml, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/templates/deployment-worker.yaml, charts/substra-backend/values.yaml, skaffold.yaml
Companion PR : https://github.com/SubstraFoundation/hlf-k8s/pull/17
=> Remove orderer configuration from substra backend

populate.py
It has not been updated in the following PR https://github.com/SubstraFoundation/substra-backend/pull/57
=> Fix populate

backend/substrapp/serializers/ledger/computeplan/serializer.py, backend/substrapp/tests/views/tests_views_computeplan.py
=> Make *tuples optional for a compute plan

backend/backend/settings/dev.py
This speeds up this e2e test: https://github.com/SubstraFoundation/substra-tests/pull/39
=> compute task: don't wait between retries on dev

backend/backend/settings/dev.py
This will speed up e2e tests (see https://github.com/SubstraFoundation/substra-tests/pull/39)
=> only retry compute tasks once on dev

backend/events/apps.py
=> Handle event from failed transactions

backend/substrapp/views/objective.py
=> Fix 500 on wrong pk for leaderbord

charts/substra-backend/templates/deployment-server.yaml
=> Add statics shared volume

backend/substrapp/ledger_utils.py
Attempted fix at #77 
This introduces a new exception, `LedgerUnavailable` and adds a retry on it.
=> Add retry on new LedgerUnavailable error

backend/substrapp/ledger_utils.py
@inalgnu and I ran into a new error from the ledger: "PHANTOM READ CONFLICT".
This PR adds a retry in case this error is returned by the ledger. The status code attached to the error is really just a placeholder, we didn't take the time to properly investigate what the code should be. If you have an opinion about it please feel free to share!
=> Retry ledger call on phantom read conflict

backend/substrapp/serializers/ledger/computeplan/serializer.py
Link with https://github.com/SubstraFoundation/substra-chaincode/pull/71 and https://github.com/SubstraFoundation/substra-tests/pull/54
=> Add compute plan tag

backend/substrapp/ledger_utils.py
fix https://github.com/SubstraFoundation/substra-backend/issues/103
=> Remove status check before retries

backend/backend/settings/deps/ledger.py, backend/substrapp/ledger_utils.py
~~Also decrease its value from 45 to 5.~~
This setting can also be set using an env var.
=> Add ledger wait for event timeout in settings

.dockerignore
Speed up docker build for Docker for Mac
=> Add unecessary directories to dockerignore

backend/requirements.txt
Update requests version to fix deprecation warning
=> Update requests version

.travis.yml, backend/backend/urls.py, backend/substrapp/management/tests/tests_bulkcreatedatasample.py, backend/substrapp/serializers/datasample.py, backend/substrapp/tasks/exception_handler.py, backend/substrapp/tests/query/tests_query_datasample.py, backend/substrapp/tests/tests_exception.py, backend/substrapp/tests/tests_tasks.py, backend/substrapp/tests/views/tests_views_task.py, backend/substrapp/tests/views/tests_views_tuples.py, backend/substrapp/views/filters_utils.py, backend/users/views/user.py
- add case check to travis conf
- fix incorrect uses of camelCase
- mark ok uses of camelCase with `# noqa`
=> Fix camelcase

backend/substrapp/ledger_utils.py
This fixes connection leaks from the backend to the peers and the orderer.
If we look at the number of open TCP connections on `org-1-peer-1-backend-server` after running `substra-tests/make test`. Without the fix:
```
90 network-orderer.or:7050
720 network-org-1-peer:7051
91 network-org-2-peer:7051
```
(Note that these connections don't close themselves after a while - I waited up to 30 min)
With the fix:
```
1 network-org-1-peer:7051
```
It looks like this fix solves _some_ of the memory leaks (but not all). Memory increase in `minikube` after running `make test`:
- Without fix: 400 MB
- With fix: 80 MB
(it's kind of hard to measure, so those numbers are just indicative)
We could close the channels in instead of sequentially, it should be a tad faster.
We could consider adding the …
=> Fix connection leaks

backend/substrapp/tasks/utils.py, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/deployment-worker.yaml
Fixes https://github.com/SubstraFoundation/substra-backend/issues/127
=> Specify docker image tag to use for GPU discovery

backend/substrapp/views/aggregatealgo.py, backend/substrapp/views/algo.py, backend/substrapp/views/compositealgo.py, backend/substrapp/views/datamanager.py, backend/substrapp/views/objective.py
#134 was merged a bit fast, this PR adds an explanation.
=> Add comment explaining description route change

backend/substrapp/ledger_utils.py, backend/substrapp/tasks/tasks.py
Chaincode PR https://github.com/SubstraFoundation/substra-chaincode/pull/84
=> Remove storage address from head model

backend/substrapp/tasks/tasks.py
- use compute plan tag to link secrets and compute plan (tuple tag was used)
- raise error if no secret match tag
- fix typo in label selector
=> Secrets plumbing fixes

charts/substra-backend/Chart.yaml, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/values.yaml
It may be better to have this in the values.yaml instead of default ! What do you think
=> Update server values

backend/substrapp/tasks/tasks.py
The celery worker process may be sigkill by the system.
This PR provides a way to retry the task because of that ! 
You can try it by launching a substra network and killing (in the worker) a celery process with `ps -awwwx | grep [c]elery | tail -n 1 | awk '{print $1}' | xargs kill -9` and see the logs to see that the task will comes back
http://docs.celeryproject.org/en/latest/userguide/configuration.html#task-reject-on-worker-lost
https://github.com/celery/celery/issues/5106
=> Add celery task option for more resiliency in the compute task function

backend/substrapp/tasks/tasks.py, backend/substrapp/tasks/utils.py, backend/substrapp/utils.py
This PR adds timing logs to lots of worker methods in order to better see what is impacting the overall execution time.
It also adds the following optimizations:
- parallel download of inmodels
- only build docker image if it doesn't already exists
=> Timing logs and optimizations

backend/substrapp/tasks/tasks.py
=> fix delete secrets

backend/events/apps.py, backend/substrapp/tasks/tasks.py
Handle new events structure. Add removal of local volume and algo ima…ges at the end of compute plan.
Companion PR https://github.com/SubstraFoundation/substra-chaincode/pull/98
=> Implement compute plan events

backend/substrapp/tasks/tasks.py
This is following local folder removal after receiving a chaincode event #166 extending it to the chain keys volume.
=> Computeplan remove chainkeys volume

backend/substrapp/ledger_utils.py
As we use a distributed ledger, state of the ledger could not be the same at a time on each node.
For instance, between two nodes
```
WORKER - NODE 1
INFO 2020-02-28 10:24:46,653 substrapp.ledger_utils 5024 140147702019904 smartcontract invoke:logStartAggregate; elaps=298.21ms; error=LedgerError 
CHAINCODE - NODE 2
[BLOCK 3736]
2020-02-28 10:24:46.181 UTC [substra-chaincode] Infof -> INFO 2388[0m aggregatetuple a4a44bff613ab053825c2185b168fb1c4985cfa764721c9051dcea3718d46eee status updated: todo (from=waiting)
2020-02-28 10:24:46.185 UTC [substra-chaincode] Infof -> INFO 2389[0m Response from chaincode: main.outputCompositeTraintuple{Key:"42312efd79632cf0e9167824a86d3a3a3ffbeb36d62f6f2cbc2b2c2abc9a4c70", Algo:(*main.HashDressName)(0xc0001900f0), Creator:"Org1MSP", …
```
=> Fix LedgerStatusError and retry on such error

backend/backend/settings/deps/ledger.py, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/configmap-server.yaml
Companion PR https://github.com/SubstraFoundation/hlf-k8s/pull/37
=> No limit on grpc client

backend/substrapp/tasks/tasks.py, backend/substrapp/tasks/utils.py, backend/substrapp/utils.py
During a test, we see that exceptions in thread are not handled correctly.
Moreover there is a proper way to handle streaming content from requests : https://stackoverflow.com/a/16696317
=> Improve fetch models error handling and content stream

charts/substra-backend/values.yaml
The Configmap added by #190 was not correctly named.
=> Fix private ca configMap name

backend/events/apps.py, backend/substrapp/serializers/ledger/computeplan/serializer.py, backend/substrapp/tasks/tasks.py, docker/start.py
Companion PR : https://github.com/SubstraFoundation/substra-tests/pull/86 & https://github.com/SubstraFoundation/substra-chaincode/pull/106 & https://github.com/SubstraFoundation/substra/pull/135
=> Remove listed models from Compute plan event

backend/requirements.txt
* e2e tests passing ✅ (`substra-tests`)
* unit tests passing ✅ 
* clicking around the browsable API working fine ✅ 
* frontend working dine ✅
=> Update Django to 2.2.11 (previous 2.2.10)

backend/backend/settings/common.py, backend/backend/urls.py, backend/substrapp/admin.py
This PR removes django admin from the project.
=> Remove django admin

backend/libs/gen_secret_key.py
Our secrets were generated using the `random` lib, which is not suitable for cryptographic purposes. One suggestion was to use `os.urandom` instead, but I discovered the `secrets` library from the standard library: https://docs.python.org/3.6/library/secrets.html
As the `secrets` introduction states:
> The secrets module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.
> In particularly, secrets should be used in preference to the default pseudo-random number generator in the random module, which is designed for modelling and simulation, not security or cryptography.
I opted for secrets instead of urandom as it made for a very simple use.
=> Use the secrets lib for secret generation

charts/substra-backend/Chart.yaml, charts/substra-backend/templates/rbac.yaml
Follow-up to https://github.com/SubstraFoundation/substra-backend/pull/184
=> Fix worker rbac name mismatch

backend/backend/settings/common.py, backend/substrapp/tasks/tasks.py, backend/substrapp/tasks/utils.py, backend/substrapp/tests/tests_tasks.py
- Remove resources manager
- Improve fetch memory limit
- Enhance logs
=> Improve worker

backend/substrapp/tasks/tasks.py, backend/substrapp/tests/common.py
Proposal Fix https://github.com/SubstraFoundation/substra-backend/issues/217
Some improvement to a better handling of those issues
=> Improve error handling

README.md, backend/requirements-dev.txt
Fix https://github.com/SubstraFoundation/substra-backend/issues/198
=> Add dev requirements

skaffold.yaml
Companion PR: https://github.com/SubstraFoundation/hlf-k8s/pull/58
=> Update skaffold to match hlf-k8s (remove-aliases)

skaffold.yaml
=> Increase throttle values in local

backend/substrapp/tasks/k8s_backend.py
Add a pod affinity to the worker for every pods started by the worker.
=> Add affinity to all pods

docker/celerybeat/Dockerfile, docker/celeryworker/Dockerfile, docker/flower/Dockerfile, docker/substra-backend/Dockerfile
Using `COPY --chown` does not seem to work with gcloud build (CI with substra-tests).
=> Use RUN chown instead of COPY --chown

backend/backend/settings/common.py, backend/substrapp/tasks/k8s_backend.py, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/deployment-worker.yaml, charts/substra-backend/templates/job-image-builder-warmer.yaml, charts/substra-backend/templates/job-registry-prepopulate.yaml, charts/substra-backend/values.yaml
- prepopulate local registry from custom registry (with auth)
- add mirror registry option for kaniko builds
- pull compute task images from custom registry (kaniko, busybox)
=> no internet

backend/substrapp/tests/generate_assets.py, populate.py
Companion PR to https://github.com/SubstraFoundation/substra/pull/138
=> Use substra.Client new login method

backend/substrapp/tasks/tasks.py
See discussion [here](https://github.com/SubstraFoundation/substra-backend/pull/285)
=> Ignore error on subtuple retrieval in prepare_tuple

backend/substrapp/tasks/tasks.py
Fix https://github.com/SubstraFoundation/substra-backend/issues/253
=> Fix image removal

skaffold.yaml
By fixing it, redo a skaffold run / dev does not redeploy rabbitmq
=> Fix rabbitmq erlang cookie value

backend/substrapp/tasks/tasks.py
Return early and don't attempt to delete models if there's nothing to delete
Needs to be cherry-picked into https://github.com/SubstraFoundation/substra-backend/pull/301
﻿
=> Remove intermediary models: don't display empty log lines

charts/substra-backend/Chart.yaml, charts/substra-backend/templates/deployment-worker.yaml, charts/substra-backend/templates/storage.yaml, charts/substra-backend/values.yaml, skaffold.yaml
Multiple fixes after k8s-backend #299 was merged :
- Remove docker socket mount in substra-backend chart 
- Add server medias hostPath value
=> K8S Backend fixup

backend/backend/settings/deps/raven.py, backend/backend/settings/prod.py, backend/requirements.txt, docker/celerybeat/Dockerfile, docker/celeryworker/Dockerfile, docker/flower/Dockerfile, docker/substra-backend/Dockerfile
Update requirements (remove useless package, re-order)
Speed up docker build (https://github.com/grpc/grpc/issues/22815)
Remove unused sentry/raven dependencies
We will need to put a tag for the new docker images !
=> Improvements

backend/substrapp/tests/views/tests_views_algo.py, backend/substrapp/tests/views/tests_views_compositealgo.py, backend/substrapp/tests/views/tests_views_compositetraintuples.py, backend/substrapp/tests/views/tests_views_computeplan.py, backend/substrapp/tests/views/tests_views_datamanager.py, backend/substrapp/tests/views/tests_views_model.py, backend/substrapp/tests/views/tests_views_objective.py, backend/substrapp/tests/views/tests_views_tuples.py, backend/substrapp/views/aggregatealgo.py, backend/substrapp/views/aggregatetuple.py, backend/substrapp/views/algo.py, backend/substrapp/views/compositealgo.py, backend/substrapp/views/compositetraintuple.py, backend/substrapp/views/computeplan.py, backend/substrapp/views/datamanager.py, backend/substrapp/views/datasample.py, backend/substrapp/views/filters_utils.py, backend/substrapp/views/model.py, backend/substrapp/views/objective.py, backend/substrapp/views/testtuple.py, backend/substrapp/views/traintuple.py
Companion PR:
https://github.com/SubstraFoundation/substra/pull/223
https://github.com/SubstraFoundation/substra-frontend/pull/81
=> Remove nested list in api result

backend/events/apps.py, backend/substrapp/ledger_utils.py, backend/substrapp/serializers/ledger/aggregatealgo/serializer.py, backend/substrapp/serializers/ledger/aggregatetuple/serializer.py, backend/substrapp/serializers/ledger/algo/serializer.py, backend/substrapp/serializers/ledger/compositealgo/serializer.py, backend/substrapp/serializers/ledger/compositetraintuple/serializer.py, backend/substrapp/serializers/ledger/computeplan/serializer.py, backend/substrapp/serializers/ledger/datamanager/serializer.py, backend/substrapp/serializers/ledger/datasample/serializer.py, backend/substrapp/serializers/ledger/objective/serializer.py, backend/substrapp/serializers/ledger/testtuple/serializer.py, backend/substrapp/serializers/ledger/traintuple/serializer.py, backend/substrapp/tasks/tasks.py, backend/substrapp/tests/assets.py, backend/substrapp/tests/views/tests_views_objective.py, backend/substrapp/views/datamanager.py, backend/substrapp/views/objective.py
Follow up of https://github.com/SubstraFoundation/substra-backend/pull/315
Companion PR:
https://github.com/SubstraFoundation/substra-chaincode/pull/125
=> Update snake case as chaincode use snake case for input/output

backend/backend/settings/common.py, backend/requirements.txt, backend/substrapp/tasks/k8s_backend.py, backend/substrapp/utils.py, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/templates/deployment-worker.yaml, charts/substra-backend/values.yaml
python-requests doesn't have a timeout by default ([source](https://requests.readthedocs.io/en/master/user/advanced/#timeouts)) :scream:
=> Add timeout to python-requests

skaffold.yaml, values/backend-org-1.yaml, values/backend-org-2.yaml
In order to have a simpler skaffold file and add the possibility to deploy with helm only, we extract helm values from skaffold file into separate values files.
@natct10 Do we need to update the documentation for that part ?
=> Extract values for skaffold

.travis.yml
=> Remove target dev branch from travis config

backend/substrapp/tasks/tasks.py, backend/substrapp/tasks/utils.py
It looks like using threads to download models in parallel is slower than Process.
For 11 * 2 Go, 
**Thread** 
```
#1 -  49.08039045333862 seconds - 2097152000                                                               
#5 - 67.21909880638123 seconds - 2097152000                                                               
#2 - 69.7494068145752 seconds - 2097152000                                                                
#4 - 73.38624572753906 seconds - 2097152000                                                               
#3 - 76.63423752784729 seconds - 2097152000                                                               
#6 - 78.72280073165894 seconds - 2097152000                                                               
#7 - 81.33725309371948 seconds - …
```
=> Change from Thread to Process

.github/workflows/helm.yml, charts/substra-backend/README.md
Removed a trailing `;fi'` in the workflow
Changed the token we used for an ssh key.
Fix helm publication.
The workflow was executed on this branch.
resulting commit https://github.com/SubstraFoundation/charts/commit/0917158e0dd135d44145a3bb089c7911ff151b0b.
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
=> Fix helm publish

backend/libs/health_check_middleware.py, backend/node-register/apps.py
In case of multichannel, if one channel has a issue, the other can not be used. With that PR, it's now possible ! 
None
None
Launch substra e2e test :) 
None
None
=> Put register node in subprocess

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/values.yaml
Fix issue when deploying with default value
=> Fix default service value for docker-registry

backend/backend/settings/common.py, backend/backend/settings/deps/cors.py, backend/backend/settings/prod.py, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/deployment-server.yaml, values/backend-org-1.yaml, values/backend-org-2.yaml
Cors and allow host are too permissive. Restrict them with env variable and no authorisation by default.
None
None
Launch e2e tests from substra-tests.
None
=> Fix cors and host authorization

backend/requirements.txt
These updates contains security fixes.
I successfully ran substra-test on a local deployment.
=> chore: update django and django-celery-results

backend/requirements.txt
This updates cryptography package to the most recent version as of today.
=> chore: update cryptography to its latest release

backend/backend/celery.py, backend/substrapp/tasks/k8s_backend.py, backend/substrapp/tasks/tasks.py, backend/substrapp/tasks/utils.py, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/templates/deployment-celerybeat.yaml, charts/substra-backend/templates/deployment-scheduler.yaml, charts/substra-backend/templates/rbac.yaml, charts/substra-backend/values.yaml
Similar to #399 but in python
Add celery docker-registry cleaning tasks + fix celery beat and scheduler
Fix https://github.com/SubstraFoundation/substra-backend/issues/398
=> feat: add registry cleaning tasks

.github/workflows/container-image-backend.yml, .github/workflows/gcr.yml
Update the backend image workflow to publish package under the org.
=> ci: fix backend image build

.github/workflows/container-image-metrics.yml
Update the backend metrics image workflow to publish package under the org.
=> ci: fix metrics image workflow

skaffold.yaml
The org is now named Substra.
Running the chart locally.
=> chore: rename image repository in skaffold file

backend/api/tests/views/test_utils.py, backend/api/tests/views/test_views_algo.py, backend/api/tests/views/test_views_authentication.py, backend/api/tests/views/test_views_compute_plan_graph.py, backend/api/tests/views/test_views_computeplan.py, backend/api/tests/views/test_views_computetask.py, backend/api/tests/views/test_views_datamanager.py, backend/api/tests/views/test_views_datasample.py, backend/api/tests/views/test_views_metadata.py, backend/api/tests/views/test_views_model.py, backend/api/tests/views/test_views_newsfeed.py, backend/api/tests/views/test_views_performance.py, backend/api/tests/views/test_views_task_profiling.py, backend/api/views/algo.py, backend/api/views/compute_plan_graph.py, backend/api/views/computeplan.py, backend/api/views/computetask.py, backend/api/views/computetask_logs.py, backend/api/views/datamanager.py, backend/api/views/datasample.py, backend/api/views/metadata.py, backend/api/views/model.py, backend/api/views/newsfeed.py, backend/api/views/performance.py, backend/api/views/utils.py
---
- https://app.asana.com/0/0/1202951505377093
=> chore: aliasing substrapp django models

.github/labeler.yml, .github/workflows/labeler.yml
It should help navigating and filtering PRs.
=> ci: auto label PRs

charts/substra-backend/README.md
Use http links for the changelog and upgrade documentation.
It's ok if the CI does not pass, it will be upgraded when someone will upgrade the chart later.
With the current solution there is a broken link to the changelog on https://artifacthub.io/packages/helm/substra/substra-backend/
=> docs: update the changelog link and add an upgrade section

examples/values/backend-org-1.yaml, examples/values/backend-org-2.yaml
Reference the correct image of substra-tools.
We forgot to change this reference during the migration.
Starting the backend locally the image loaded correctly.
=> fix: example values for substra-tools

backend/orchestrator/client.py
Remove dead code from the orchestrator client.
This code was unused, not tested so it's not worth to keep it.
end to end tests.
=> chore: remove unused code from the orchestrator client

backend/substrapp/compute_tasks/asset_buffer.py, backend/substrapp/tests/compute_tasks/test_asset_buffer.py
Change a bit how models are downloaded.
One less call to the orchestrator and better typing.
e2e tests
=> refactor: asset buffer

CHANGELOG.md, backend/api/events/sync.py, backend/api/management/commands/generate_fixtures.py, backend/api/serializers/computetask.py, backend/api/tests/asset_factory.py, backend/api/tests/views/test_views_computetask.py
Use ComputeTaskOutputAsset instances to serialize the output assets in API response.
---
- https://app.asana.com/0/0/1202936323744418
=> feat: api response based on output asset

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/values.yaml
=> chore: release 0.31.0

CHANGELOG.md
It was forgotten in 078f22f76c437ee7913d056fcd737ba41d81dd22 (#436)
=> docs(changelog): entry for model categories removal

backend/substrapp/compute_tasks/outputs.py, backend/substrapp/tests/compute_tasks/test_outputs.py
Model categories have been removed.
Untested, relying on CI 🤞
=> fix: remove temporary model category stub

.github/workflows/migration.yml, CHANGELOG.md
Test forward migrations in the CI between the main branch and any new pull request. The script is inspired by the manual test workflow as described in the [`doc`](https://github.com/Substra/substra-backend/blob/main/docs/test_migrations.md)
This aim to discover migration issues earlier that upon performing substra upgrade with substra-generator as such: https://owkin.slack.com/archives/C02JQ8DN7R8/p1653308666645529
Asana [card](https://app.asana.com/0/1201599852028640/1202320710297939)
- [ x] [changelog](../CHANGELOG.md) was updated with notable changes
When a migration file is added in the PR the github action [pass successfully](https://github.com/Substra/substra-backend/actions/runs/3142053150)
=> chore: add migration test step

backend/api/tests/views/test_views_computetask.py
Factorize inputs outputs cross categories in preparation of the new task endpoint. #476 
E2e tests not needed as only test modules are changed.
=> chore: clean task tests

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/values.yaml
=> chore: release 0.32.0

backend/api/management/commands/generate_fixtures.py, backend/api/tests/asset_factory.py, backend/api/tests/views/test_views_algo.py, backend/api/tests/views/test_views_computetask.py
Improve test data with realistic CP topologies.
```python
python manage.py generate_fixtures
```
=> chore: improve test data with real cp topologies

CHANGELOG.md, backend/api/views/model.py, backend/substrapp/compute_tasks/outputs.py, backend/substrapp/tests/compute_tasks/test_outputs.py
Signed-off-by: Kelvin Moutet <kelvin.moutet@owkin.com>
Create a post api for model files and use it in for the compute task output
Unit tests
E2E tests
=> feat: create and use create model api for compute task output

docs/authentication.md
Init documentation on API authentication.
---
- https://app.asana.com/0/0/1202963105406679
=> docs: add auth doc

CHANGELOG.md, backend/users/tests/test_user.py, backend/users/views/user.py
Related to https://github.com/Substra/substra-frontend/issues/130
Adds a role filter to the users list. 
Tested through DRF UI and unit tests
=> feat: filter users by role

.github/CODEOWNERS, CHANGELOG.md
Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>
=> chore: update code owners

CHANGELOG.md, Makefile, backend/substrapp/compute_tasks/command.py, backend/substrapp/tests/compute_tasks/test_command.py
- https://github.com/Substra/substra-backend/pull/548 (main)
- https://github.com/Substra/substra-tools/pull/75
- https://github.com/Substra/substra/pull/329
Asana card https://app.asana.com/0/1202209633046022/1203021914361542/f
=> chore: rank in task properties

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/values.yaml
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
Release 0.34.0
=> chore: bump app version

backend/api/migrations/0042_computeplan_creator.py
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
=> fix: rename migration

charts/substra-backend/Chart.yaml
Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>
=> chore: update chart mainteners

CHANGELOG.md, backend/orchestrator/computetask_pb2.pyi, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/values.yaml
=> chore: release 0.35.0

skaffold.yaml
Signed-off-by: Guilhem Barthes <guilhem.barthes@owkin.com>
The indentation in the section `profiles` (specifically line [66)](https://github.com/Substra/substra-backend/pull/588/files#diff-cb88f836d7d2eec7bccbed73c47a452b8eb3e376b02bae73ecae449bba96214aL66) in `skaffold.yaml` makes the CI fails.
=> fix(skaffold): fix indentation in skaffold.yaml

backend/requirements.txt
Checking to see if #565 is needed
CI below
=> chore: remove unused ipython dependencies

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml
=> chore: release 0.36.1

README.md
Adding the link to the hack for linking `uWSGI` as it provides more context on the how and why. 
And adding a mention on how to install `gprcio` with conda.
=> chore: add instructions for dev installation with conda in readme

backend/api/migrations/0051_alter_performance_unique_together_and_more.py
Fix migration 51 by saving the compute task output impacted by the identifier of the performance
=> fix: migration 0051

backend/api/migrations/0052_remove_metric_from_performance.py
=> fix: remove get() in migration 52

backend/api/migrations/0051_alter_performance_unique_together_and_more.py
=> fix: migrate metric output identifier

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml
=> chore: release 0.38.0

pyproject.toml
See linear description
Fixes FL-1043
=> fix: implement change in stacklevel `DeprecationWarning` is raised

.gitignore, CHANGELOG.md, backend/orchestrator/resources.py, backend/requirements.txt, backend/substrapp/tasks/tasks_compute_task.py, backend/substrapp/tests/tasks/test_compute_task.py
- https://github.com/Substra/substra/pull/375 (main)
- https://github.com/Substra/substrafl/pull/159
- https://github.com/Substra/substra-tests/pull/272
- https://github.com/Substra/substra-backend/pull/718
=> chore: bump to pydantic 2.3.0

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml
=> chore: release 0.42.0

CHANGELOG.md, examples/secrets/secret-orchestrator-tls-org-3-client-pair.yaml, examples/secrets/skaffold.yaml, examples/values/backend-org-1.yaml, examples/values/backend-org-2.yaml, examples/values/backend-org-3.yaml, examples/values/serviceAccounts/serviceAccount-org-3.yaml, examples/values/serviceAccounts/skaffold.yaml, skaffold.yaml
Propose a Skaffold profile to create 3 orgs in standalone mode.
This profile is called "three_orgs".
Sorry about linter....
closes FL-1208
CI + Locally
- https://github.com/Substra/substra-backend/pull/733
- https://github.com/Substra/orchestrator/pull/280
- https://github.com/Substra/substra-documentation/pull/365
=> feat: add three org profile

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml
=> chore: release 0.42.1

CHANGELOG.md, backend/backend/settings/common.py, backend/backend/settings/localdev.py, backend/backend/settings/prod.py, backend/backend/settings/test.py, backend/backend/settings/worker/events/dev.py
Replace the default for Debug. Currently by default it's ` True` , changed to ` False` . Fixes FL-1236.
=> fix: Change `DEBUG=True`  by default to `DEBUG=False`

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/_helpers.tpl, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/templates/statefulset-worker.yaml
`wait-minio` inside of  `initContainer` moved to the helm helper templates
=> refactor(helm): refactor wait-minio

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/_helpers.tpl, charts/substra-backend/templates/deployment-api-events.yaml, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/templates/deployment-worker-events.yaml, charts/substra-backend/templates/statefulset-worker.yaml
=> refactor(charts): Move wait-postgresql to Helm chart helper templates

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/_helpers.tpl
=> fix(helm): Add environment values for wait-postgresql

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/_helpers.tpl, charts/substra-backend/templates/deployment-api-events.yaml, charts/substra-backend/templates/deployment-scheduler-worker.yaml, charts/substra-backend/templates/deployment-server.yaml, charts/substra-backend/templates/deployment-worker-events.yaml, charts/substra-backend/templates/statefulset-worker.yaml
- `add-ca-cert` `initContainer`  refactored as Helm helper template
- `wait-init-migrations` `initContainer` refactored to Helm helper template
=> refactor(helm): refactor initContainers in Helm helper templates

CHANGELOG.md, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml
=> chore: release 0.42.2

.github/workflows/docker-build.yaml
Fix[ the syntax error](https://github.com/Substra/substra-backend/actions/runs/6574521039) related to the missing default value for force-push input caused by #769
=> fix(ci): fix syntax issue in docker-build

backend/substrapp/tasks/task.py
=> fix: asset_failure_report

CHANGELOG.md, backend/api/views/failed_asset_logs.py
=> fix: convert uuid to str for downloading logs

CHANGELOG.md, Makefile, backend/dev-requirements.txt, backend/image_transfer/__init__.py, backend/image_transfer/common.py, backend/image_transfer/decoder.py, backend/image_transfer/encoder.py, backend/image_transfer/exceptions.py, backend/image_transfer/tests/Dockerfile, backend/image_transfer/tests/conftest.py, backend/image_transfer/tests/test_decoder.py, backend/image_transfer/tests/test_encoder.py, pyproject.toml
=> feat: refactor image transfer and add tests

README.md
=> chore: rm hlf-k8s mention on readme

.pre-commit-config.yaml
Update `flake8` in `pre-commit` to avoid error due to internal changes in the library. /!\ Developers may have to update pre-commit after this change
=> fix: update flake8 to avoid errors due to some internal library changes

.github/workflows/helm.yml
=> chore: add workflow_dispatch on helm publish

.github/workflows/helm.yml
=> fix: add `secrets: inherit`

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.lock, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/_helpers.tpl, charts/substra-backend/templates/configmap-settings.yaml, charts/substra-backend/templates/secret-objectstore.yaml, charts/substra-backend/templates/statefulset-builder.yaml, charts/substra-backend/templates/statefulset-worker.yaml, charts/substra-backend/values.yaml
=> feat: optional minio + add s3 support with localstack

.github/workflows/helm.yml
=> chore: add missing repo

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.lock, charts/substra-backend/Chart.yaml
=> chore(charts): bump redis and common chart versions

CHANGELOG.md, backend/backend/settings/mods/oidc.py, backend/users/authentication.py, docs/settings.md
=> fix: add timeouts on OIDC requests

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/_helpers.tpl, charts/substra-backend/templates/deployment-server.yaml
=> fix: increase timeout wait min io container

backend/api/migrations/0059_data_migration_computeplan.py
=> fix: add data migration for computeplan status

backend/api/migrations/0058_alter_compute_task_status.py
=> fix: migration changed `category` to `status`

README.md
=> docs(README): fix badge & typo

docker/substra-backend/Dockerfile
closes FL-1494
Fix the 3 CVE said as "fixable" by Harbor.
Still 1 critical and 20 high
=> chore: fix fixable CVE in backend

backend/substrapp/compute_tasks/image_builder.py
=> [sub] fix: wrong secret name

backend/substrapp/apps.py
=> [sub]fix: add ca-certificate creation on startup

backend/builder/image_builder/image_builder.py, backend/substrapp/compute_tasks/compute_pod.py, backend/substrapp/kubernetes_utils.py, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/templates/deployment-api-events.yaml, charts/substra-backend/templates/deployment-registry-prepopulate.yaml, charts/substra-backend/templates/deployment-worker-events.yaml, charts/substra-backend/values.yaml
=> chore: add limits and requests to pods

backend/builder/image_builder/image_builder.py, backend/substrapp/compute_tasks/compute_pod.py, backend/substrapp/kubernetes_utils.py, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/templates/deployment-api-events.yaml, charts/substra-backend/templates/deployment-registry-prepopulate.yaml, charts/substra-backend/templates/deployment-worker-events.yaml, charts/substra-backend/values.yaml
This reverts commit d030646ea9c63565e246ea7d678763f8ae3ab952.
=> revert: add limits and requests to pods (#867)

backend/requirements.txt
=> chore: exclude versions requests 2.32.*

backend/substrapp/kubernetes_utils.py, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/resources-dev.yaml, charts/substra-backend/values.yaml, skaffold.yaml
part of FL-1562
- https://github.com/owkin/substra-ci/pull/161
=> chore: overwrite dev ressources in separate yaml

backend/substrapp/docker_registry.py
=> chore: accept oci manifests

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/README.md, charts/substra-backend/templates/networkpolicy-internet.yaml, charts/substra-backend/templates/networkpolicy-orchestrator-client.yaml, charts/substra-backend/values.yaml, examples/values/backend-org-1.yaml, examples/values/backend-org-2.yaml, examples/values/backend-org-3.yaml
=> fix: network policy gcp

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/networkpolicy-orchestrator-client.yaml
=> fix: allow communication with internet when orchestrator is remote

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/networkpolicy-orchestrator-client.yaml
=> fix: whitespace removal in networkpolicy orchestrator client

CHANGELOG.md, changes/1517.removed, changes/1520.added, changes/862.changed, changes/862.fixed, changes/862.removed, changes/866.changed, changes/877.added, changes/878.changed, changes/888.added, changes/892.added, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml
=> chore: release 0.46.0

backend/builder/tasks/tasks_build_image.py, backend/builder/tests/test_task_build_image.py, backend/substrapp/tasks/tasks_compute_task.py, changes/911.fixed
=> feat: catch all exceptions on builder to fail properly

backend/builder/tasks/tasks_build_image.py, changes/927.fixed
=> fix: repackaging `BuildError`

charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/values.yaml
=> fix: remove postgresql user default

backend/image_transfer/decoder.py, backend/image_transfer/encoder.py, backend/substrapp/compute_tasks/execute.py, backend/substrapp/docker_registry.py, backend/substrapp/tasks/tasks_save_image.py, backend/substrapp/tests/tasks/test_save_image.py, changes/926.added, changes/926.fixed
=> feat: repackage 412 Harbor error into a user-friendly error

backend/api/events/sync.py, changes/932.fixed
=> fix: casting when receiving `FunctionProfilingStep`

charts/substra-backend/CHANGELOG.md
=> fix: chart changelog date

backend/image_transfer/decoder.py, backend/substrapp/compute_tasks/execute.py, backend/substrapp/compute_tasks/image_builder.py, changes/934.changed, changes/934.fixed
=> chore: improve check for image download

backend/requirements.txt, changes/1672.fixed
=> fix: pin pyopenssl to prevent deprecation warnings

.github/dependabot.yml
=> feat: add groups in `dependabot.yml`

.github/dependabot.yml
=> fix(dependabot): remove YAML anchors in `dependabot.yaml`

.github/dependabot.yml
=> chore: add `docker` to `production-dependencies`

.github/dependabot.yml
=> fix(deps): remove docker from production dependencies pattern

backend/builder/image_builder/image_builder.py
=> fix: kaniko deprecated options

CHANGELOG.md, backend/users/management/commands/sync_users.py, changes/1029.fixed, charts/substra-backend/CHANGELOG.md, charts/substra-backend/Chart.yaml, charts/substra-backend/templates/job-migrations.yaml
Fixes RP-1519
Locally, on skaffold
=> fix: check if OIDC is activated before deleting users

CHANGELOG.md, changes/1029.fixed
=> chore: release 1.0.1-rc1
